## Importing functions

In [1]:
from functions.gpkg_funcs import (
    import_gpkg_func,
    reproject_gpkg_func,
)

from functions.idx_pixel_count_funcs import (
    idx_per_row_area_func,
)

from functions.idx_to_gdf_or_plot_funcs import (
    idx_df_to_gdf_func,
)

from functions.training_validation_split_funcs import (
    training_validation_split_func,
    idx_to_carto_training_gdf_func,
)

## Setting Directory

In [2]:
from paths.OG_paths import(
    #######################################
    #  03_training_validation_data_split  #
    #######################################
    # | n01_build_selected_pixels_idx_dfs |
    # +===================================+
    # --- manual inspected pixeled gpkg --- #    
    habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path,
    
    # --- selected pixels IDX dfs --- #
    idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD1_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD2_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD3_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD4_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD5_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__s1_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__s2_plusOW_p80__selected__gelderland__tmp2__df_path,


    # +=====================================+
    # | n03_training_validation_split_carto |
    # +=====================================+
    # --- idx training validation dfs --- #
    #WD1
    idx__WD1_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path,
    idx__WD1_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path,
    #WD2
    idx__WD2_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path,
    idx__WD2_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path,
    #WD3
    idx__WD3_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path,
    idx__WD3_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path,
    #WD4
    idx__WD4_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path,
    idx__WD4_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path,
    #WD5
    idx__WD5_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path,
    idx__WD5_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path,
    # S1
    idx__s1_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path,
    idx__s1_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path,
    # S2
    idx__s2_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path,
    idx__s2_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path,

    # --- training validation GPKGs RD --- #
    # WD1
    training_polys__WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    validation_pixels__WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    # WD2
    training_polys__WD2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    validation_pixels__WD2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    # WD3
    training_polys__WD3_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    validation_pixels__WD3_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    # WD4
    training_polys__WD4_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    validation_pixels__WD4_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    # WD5
    training_polys__WD5_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    validation_pixels__WD5_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    # S1
    training_polys__s1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    validation_pixels__s1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    # S2
    training_polys__s2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
    validation_pixels__s2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

## Importing packages

In [3]:
import pandas as pd

## Importing files

In [4]:
habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path, 
    layer='habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__layer', 
    index_col='index',
)

In [5]:
idx__FC_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD1_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD1_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD2_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD2_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD3_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD3_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD4_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD4_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD5_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD5_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__s1_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__s1_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__s2_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__s2_plusOW_p80__selected__gelderland__tmp2__df_path)

## Calculating the unique area of each pixel

_This step calculates the total area of the unique ID's. If a ID is present in multiple columns, then it is only taken into account once. Based on this a list is build that determines the amount of area that should be included in the training/validation set_

### WD1

In [6]:
WD1_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD1_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD1 areas per row:\n" + WD1_area_text)

WD1 areas per row:
Remaining: 304500.61 pixels
Wet Nature: 1537.11 pixels
Open water: 1330.00 pixels

In [7]:
WD1_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 1400,
    "Open water": 300,
}

### WD2

In [8]:
WD2_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD2_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD2 areas per row:\n" + WD2_area_text)

WD2 areas per row:
Remaining: 304500.61 pixels
Semi-Wet Nature: 1289.76 pixels
Wet Nature: 247.35 pixels
Open water: 1330.00 pixels

In [9]:
WD2_at1_dict = {
    "Remaining": 1250,
    "Wet Nature": 250,
    "Semi-Wet Nature": 500,
    "Open water": 250,
}

### WD3

In [10]:
WD3_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD3 areas per row:\n" + WD3_area_text)

WD3 areas per row:
Remaining: 122089.61 pixels
Wet Nature: 1537.11 pixels
Open water: 1330.00 pixels

In [11]:
WD3_at1_dict = {
    "Remaining": 2500,
    "Wet Nature": 1300,
    "Open water": 300,
}

In [ ]:
WD3_at2_dict = {
    "Remaining": 5000,
    "Wet Nature": 1300,
    "Open water": 500,
}

### WD4

In [12]:
WD4_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD4_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD4 areas per row:\n" + WD4_area_text)

WD4 areas per row:
Remaining: 122089.61 pixels
Semi-Wet Nature: 1289.76 pixels
Wet Nature: 247.35 pixels
Open water: 1330.00 pixels

In [13]:
WD4_at1_dict = {
    "Remaining": 1250,
    "Semi-Wet Nature": 500,
    "Wet Nature": 250,
    "Open water": 300,
}

In [41]:
WD4_at2_dict = {
    "Remaining": 3000,
    "Semi-Wet Nature": 750,
    "Wet Nature": 250,
    "Open water": 500,
}

### WD5

In [14]:
WD5_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD5_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD5 areas per row:\n" + WD5_area_text)

WD5 areas per row:
Remaining: 122089.61 pixels
Semi-Wet Nature: 1289.76 pixels
Open water: 1577.35 pixels

In [15]:
WD5_at1_dict = {
    "Remaining": 1250,
    "Semi-Wet Nature": 500,
    "Open water": 300,
}

## S1

In [16]:
s1_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__s1_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("S1 areas per row:\n" + s1_area_text)

S1 areas per row:
Geen habitattype: 182411.00 pixels
Overgangs- & trilven: 106.00 pixels
Vochtige heiden: 1283.76 pixels
Zwakgebufferde vennen: 79.00 pixels
Zure vennen: 62.35 pixels
Open water: 1330.00 pixels

In [17]:
s1_area_text_at1_dict = {
    "Remaining": 1250,
    "Semi-Wet Nature": 500,
    "Open water": 300,
}

## S2

In [18]:
s2_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__s2_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("S2 areas per row:\n" + s2_area_text)

S2 areas per row:
Geen habitattype: 182411.00 pixels
Overgangs- & trilven: 106.00 pixels
Vochtige heiden: 1283.76 pixels
Zwakbuf/Zuur ven: 141.35 pixels
Open water: 1330.00 pixels

In [19]:
s2_area_text_at1_dict = {
    "Remaining": 1250,
    "Semi-Wet Nature": 500,
    "Open water": 300,
}

## Splitting the data and saving as gpkgs

_In this step the data is split into training and validation data. Using the area dicts above._

### WD1 - Carto split

_attempt 1_

In [20]:
train_val__WD1_plusOW_p80_tmp2_cart_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD1_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD1_plusOW_p80__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD1_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
    large_polygon_threshold=36,
)

idx__WD1_plusOW_p80_tmp2_training_cart_at1__gelderland__df = train_val__WD1_plusOW_p80_tmp2_cart_at1__gelderland__list[0]
idx__WD1_plusOW_p80_tmp2_validation_cart_at1__gelderland__df = train_val__WD1_plusOW_p80_tmp2_cart_at1__gelderland__list[1]
idx__WD1_plusOW_p80_tmp2_test_cart_at1__gelderland__df = train_val__WD1_plusOW_p80_tmp2_cart_at1__gelderland__list[2]
idx__WD1_plusOW_p80_tmp2_leftover_cart_at1__gelderland__df = train_val__WD1_plusOW_p80_tmp2_cart_at1__gelderland__list[3]
idx__WD1_plusOW_p80_tmp2_summary_cart_at1__gelderland__df = train_val__WD1_plusOW_p80_tmp2_cart_at1__gelderland__list[4]

In [21]:
idx__WD1_plusOW_p80_tmp2_summary_cart_at1__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,210000.0,213200.0,90000.0,93300.0,0.0,0.0,2132,934,0,295038,0,0,122,60,0
Wet Nature,98000.0,70511.0,42000.0,14600.0,0.0,0.0,710,146,0,0,0,0,69,9,0
Open water,21000.0,23300.0,9000.0,11900.0,0.0,0.0,233,119,0,2065,0,0,14,5,0

In [22]:
# Saving the training and validation idx dfs
idx__WD1_plusOW_p80_tmp2_training_cart_at1__gelderland__df.to_pickle(
    idx__WD1_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path
)
idx__WD1_plusOW_p80_tmp2_validation_cart_at1__gelderland__df.to_pickle(
    idx__WD1_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path
)

In [23]:
# --- WD1 Carto at1 Training gpkgs --- #
training_polys__WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gdf = idx_to_carto_training_gdf_func(
    idx_df=idx__WD1_plusOW_p80_tmp2_training_cart_at1__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    out_gpkg=training_polys__WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

# --- WD1 at1 Validation gpkgs --- #
validation_pixels__WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD1_plusOW_p80_tmp2_validation_cart_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    out_gpkg=validation_pixels__WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

### WD2 -  Carto split

_attempt 1_

In [24]:
idx__WD2_plusOW_p80_tmp2_cart_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD2_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD2_plusOW_p80__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD2_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

idx__WD2_plusOW_p80_tmp2_training_cart_at1__gelderland__df = idx__WD2_plusOW_p80_tmp2_cart_at1__gelderland__list[0]
idx__WD2_plusOW_p80_tmp2_validation_cart_at1__gelderland__df = idx__WD2_plusOW_p80_tmp2_cart_at1__gelderland__list[1]
idx__WD2_plusOW_p80_tmp2_test_cart_at1__gelderland__df = idx__WD2_plusOW_p80_tmp2_cart_at1__gelderland__list[2]
idx__WD2_plusOW_p80_tmp2_leftover_cart_at1__gelderland__df = idx__WD2_plusOW_p80_tmp2_cart_at1__gelderland__list[3]
idx__WD2_plusOW_p80_tmp2_summary_cart_at1__gelderland__df = idx__WD2_plusOW_p80_tmp2_cart_at1__gelderland__list[4]

In [25]:
idx__WD2_plusOW_p80_tmp2_summary_cart_at1__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,87500.0,88500.0,37500.0,37600.0,0.0,0.0,885,376,0,300551,0,0,51,26,0
Semi-Wet Nature,35000.0,38176.0,15000.0,16500.0,0.0,0.0,384,165,0,202,0,0,44,5,0
Wet Nature,17500.0,14180.0,7500.0,4555.0,0.0,0.0,144,46,0,0,0,0,19,2,0
Open water,17500.0,18900.0,7500.0,9300.0,0.0,0.0,189,93,0,3311,0,0,10,4,0

In [26]:
# Saving the training and validation idx dfs
idx__WD2_plusOW_p80_tmp2_training_cart_at1__gelderland__df.to_pickle(
    idx__WD2_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path
    )
idx__WD2_plusOW_p80_tmp2_validation_cart_at1__gelderland__df.to_pickle(
    idx__WD2_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path
)

In [27]:
# --- WD2 at1 Training gpkgs --- #
training_polys__WD2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gdf = idx_to_carto_training_gdf_func(
    idx_df=idx__WD2_plusOW_p80_tmp2_training_cart_at1__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    out_gpkg=training_polys__WD2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

# --- WD2 at1 Validation gpkgs --- #
validation_pixels__WD2_plusOW_p80_tmp2_cart_at1__gelderland__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD2_plusOW_p80_tmp2_validation_cart_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    out_gpkg=validation_pixels__WD2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

### WD3 - Carto split

_attempt 1_

In [28]:
idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD3_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

idx__WD3_plusOW_p80_tmp2_training_cart_at1__gelderland__df = idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list[0]
idx__WD3_plusOW_p80_tmp2_validation_cart_at1__gelderland__df = idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list[1]
idx__WD3_plusOW_p80_tmp2_test_cart_at1__gelderland__df = idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list[2]
idx__WD3_plusOW_p80_tmp2_leftover_cart_at1__gelderland__df = idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list[3]
idx__WD3_plusOW_p80_tmp2_summary_cart_at1__gelderland__df = idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list[4]

In [29]:
idx__WD3_plusOW_p80_tmp2_summary_cart_at1__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,175000.0,175160.0,75000.0,75700.0,0.0,0.0,1764,757,0,114293,0,0,106,53,0
Wet Nature,91000.0,68411.0,39000.0,15200.0,0.0,0.0,689,152,0,0,0,0,69,9,0
Open water,21000.0,24300.0,9000.0,10000.0,0.0,0.0,243,100,0,1589,0,0,13,6,0

In [30]:
# Saving the training and validation idx dfs
idx__WD3_plusOW_p80_tmp2_training_cart_at1__gelderland__df.to_pickle(
    idx__WD3_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path
)
idx__WD3_plusOW_p80_tmp2_validation_cart_at1__gelderland__df.to_pickle(
    idx__WD3_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path
)

In [31]:
# --- WD3 at1 Training gpkgs --- #
training_polys__WD3_plusOW_p80_tmp2_cart_at1__gelderland__RD__gdf = idx_to_carto_training_gdf_func(
    idx_df=idx__WD3_plusOW_p80_tmp2_training_cart_at1__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    out_gpkg=training_polys__WD3_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

# --- WD3 at1 Validation gpkgs --- #
validation_pixels__WD3_plusOW_p80_tmp2_cart_at1__gelderland__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD3_plusOW_p80_tmp2_validation_cart_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    out_gpkg=validation_pixels__WD3_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

### attempt 2

In [ ]:
idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD3_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

idx__WD3_plusOW_p80_tmp2_training_cart_at1__gelderland__df = idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list[0]
idx__WD3_plusOW_p80_tmp2_validation_cart_at1__gelderland__df = idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list[1]
idx__WD3_plusOW_p80_tmp2_test_cart_at1__gelderland__df = idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list[2]
idx__WD3_plusOW_p80_tmp2_leftover_cart_at1__gelderland__df = idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list[3]
idx__WD3_plusOW_p80_tmp2_summary_cart_at1__gelderland__df = idx__WD3_plusOW_p80_tmp2_cart_at1__gelderland__list[4]

### WD4 - Carto split

_attempt 1_

In [32]:
idx__WD4_plusOW_p80_tmp2_cart_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD4_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD4_plusOW_p80__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD4_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

idx__WD4_plusOW_p80_tmp2_training_cart_at1__gelderland__df = idx__WD4_plusOW_p80_tmp2_cart_at1__gelderland__list[0]
idx__WD4_plusOW_p80_tmp2_validation_cart_at1__gelderland__df = idx__WD4_plusOW_p80_tmp2_cart_at1__gelderland__list[1]
idx__WD4_plusOW_p80_tmp2_test_cart_at1__gelderland__df = idx__WD4_plusOW_p80_tmp2_cart_at1__gelderland__list[2]
idx__WD4_plusOW_p80_tmp2_leftover_cart_at1__gelderland__df = idx__WD4_plusOW_p80_tmp2_cart_at1__gelderland__list[3]
idx__WD4_plusOW_p80_tmp2_summary_cart_at1__gelderland__df = idx__WD4_plusOW_p80_tmp2_cart_at1__gelderland__list[4]

In [33]:
idx__WD4_plusOW_p80_tmp2_summary_cart_at1__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,87500.0,89360.0,37500.0,38400.0,0.0,0.0,906,384,0,118798,0,0,54,25,0
Semi-Wet Nature,35000.0,36676.0,15000.0,15000.0,0.0,0.0,369,150,0,304,0,0,40,4,0
Wet Nature,17500.0,14455.0,7500.0,4280.0,0.0,0.0,145,45,0,0,0,0,19,2,0
Open water,21000.0,23600.0,9000.0,9800.0,0.0,0.0,236,98,0,2177,0,0,13,6,0

In [34]:
# Saving the training and validation idx dfs
idx__WD4_plusOW_p80_tmp2_training_cart_at1__gelderland__df.to_pickle(
    idx__WD4_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path
)
idx__WD4_plusOW_p80_tmp2_validation_cart_at1__gelderland__df.to_pickle(
    idx__WD4_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path
)

In [35]:
# --- WD4 at1 Training gpkgs --- #
training_polys__WD4_plusOW_p80_tmp2_cart_at1__gelderland__RD__gdf = idx_to_carto_training_gdf_func(
    idx_df=idx__WD4_plusOW_p80_tmp2_training_cart_at1__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    out_gpkg=training_polys__WD4_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

# --- WD4 at1 Validation gpkgs --- #
validation_pixels__WD4_plusOW_p80_tmp2_cart_at1__gelderland__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD4_plusOW_p80_tmp2_validation_cart_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    out_gpkg=validation_pixels__WD4_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

### WD5 - Carto split

_attempt 1_

In [36]:
idx__WD5_plusOW_p80_tmp2_cart_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD5_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD5_plusOW_p80__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD5_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

idx__WD5_plusOW_p80_tmp2_training_cart_at1__gelderland__df = idx__WD5_plusOW_p80_tmp2_cart_at1__gelderland__list[0]
idx__WD5_plusOW_p80_tmp2_validation_cart_at1__gelderland__df = idx__WD5_plusOW_p80_tmp2_cart_at1__gelderland__list[1]
idx__WD5_plusOW_p80_tmp2_test_cart_at1__gelderland__df = idx__WD5_plusOW_p80_tmp2_cart_at1__gelderland__list[2]
idx__WD5_plusOW_p80_tmp2_leftover_cart_at1__gelderland__df = idx__WD5_plusOW_p80_tmp2_cart_at1__gelderland__list[3]
idx__WD5_plusOW_p80_tmp2_summary_cart_at1__gelderland__df = idx__WD5_plusOW_p80_tmp2_cart_at1__gelderland__list[4]

In [37]:
idx__WD5_plusOW_p80_tmp2_summary_cart_at1__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,87500.0,89360.0,37500.0,38400.0,0.0,0.0,906,384,0,118798,0,0,54,25,0
Semi-Wet Nature,35000.0,36676.0,15000.0,15000.0,0.0,0.0,369,150,0,304,0,0,40,4,0
Open water,21000.0,21200.0,9000.0,9600.0,0.0,0.0,212,96,0,5405,0,0,10,4,0

In [38]:
# Saving the training and validation idx dfs
idx__WD5_plusOW_p80_tmp2_training_cart_at1__gelderland__df.to_pickle(
    idx__WD5_plusOW_p80_tmp2_training_cart_at1__gelderland__df_path
)
idx__WD5_plusOW_p80_tmp2_validation_cart_at1__gelderland__df.to_pickle(
    idx__WD5_plusOW_p80_tmp2_validation_cart_at1__gelderland__df_path
)

In [39]:
# --- WD5 at1 Training gpkgs --- #
# Carto [RD]
training_polys__WD5_plusOW_p80_tmp2_cart_at1__gelderland__RD__gdf = idx_to_carto_training_gdf_func(
    idx_df=idx__WD5_plusOW_p80_tmp2_training_cart_at1__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    out_gpkg=training_polys__WD5_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

# --- WD5 at1 Validation gpkgs --- #
validation_pixels__WD5_plusOW_p80_tmp2_cart_at1__gelderland__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD5_plusOW_p80_tmp2_validation_cart_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    out_gpkg=validation_pixels__WD5_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg_path,
)

### s1

End of the Notebook