_This notebook builds the Habitat dataframes for the different classification strategies, assigning each habitat to the respected class per division. Also, visualization information is added like color._

## Importing Functions

In [1]:
# No Functions needed in this Notebook

## Setting directory

In [2]:
from paths.OG_paths import (
    #######################################
    #            00_common_dfs            #
    #######################################
    # |    n01_habitat_reference_dfs      |
    # +===================================+ 
    habitat_reference__WD__df_path,
    habitat_reference__s__df_path,
    habitat_reference__UC__df_path,
    habitat_reference__WDNF__df_path,
)

## Importing packages

In [3]:
import pandas as pd
import pickle

pd.set_option('display.max_colwidth', None)

## Habitat Reference WD df

Changing Hab map, means changing classes in NB03_building_entropy_rasters!

In [4]:
# Linking habitat code to the display name
short_habitat_names = {
    'H0000': 'Geen habitattype',
    'H2310': 'Stuifzandheiden met struikhei',
    'H2320': 'Binnenlandse kraaheibegroeiingen',
    'H2330': 'Zandverstuivingen',
    'H3130': 'Zwakgebufferde vennen',
    'H3150': 'Meren krabbenscheer & fonteinkruiden',
    'H3160': 'Zure vennen',
    'H3260A': 'Beken & rivieren met waterplanten',
    'H3260B': 'Beken & rivieren met waterplanten',
    'H3270': 'slikkige rivieroevers',
    'H4010A': 'Vochtige heiden',
    'H4030': 'Droge heiden',
    'H5130': 'Jeneverbesstruwelen',
    'H6120': 'Stroomdalgraslanden',
    'H6230': 'Heischrale graslanden',
    'H6410': 'Blauwgraslanden',
    'H6430A': 'moerasspirea',
    'H6430B': 'Ruigten en zomen (harig wilgenroosje)',
    'H6430C': 'Droge bosranden',
    'H6510A': 'Glanshaver',
    'H6510B': 'Grote Vossenstaart',
    'H7110A': 'Actieve hoogvenen (hoogveenlandschap)',
    'H7110B': 'Actieve hoogvenen (heideveentjes)',
    'H7120': 'Herstellend hoogveen',
    'H7140A': 'Overgangs- & trilven',
    'H7150': 'Pionierveg met snavelbies',
    'H7210': 'Galigaanmoerassen',
    'H7230': 'Kalkmoerassen',
    'H9120': 'Beuken-eikenbossen',
    'H9160A': 'Eiken-haagbeukenbossen',
    'H9190': 'Oude eikenbossen',
    'H91D0': 'Hoogveenbossen',
    'H91E0A': 'Vochtige alluviale bossen zachthoutooi',
    'H91E0B': 'Vochtige alluviale bossen essen-iep',
    'H91E0C': 'Vochtige alluviale bossen beenbreek',
    'H91F0': 'Droge hardhoutooibossen',
    'LGN_OW': 'Open water',
}

habitat_reference__WD__df = pd.DataFrame(
    list(short_habitat_names.items()),
    columns=["habitatType", "habitatnaam_disp"]
)

habitat_reference__WD__df = habitat_reference__WD__df.set_index("habitatType")

In [5]:
# Adding color to the habitat_reference__WD__df
all_habitat_color_list = {
    'H0000': "#999999",
    'H2310': "#fff7b2",
    'H2330': "#e8d6c3",
    'H2320': "#8c564b",
    'H3130': "#9ed6f8",
    'H3150': "#00375f",
    'H3160': "#2e86c1",
    'H3260A': "#0c5a92",
    'H3260B': "#0c5a92",
    'H3270': "#9b4f12",
    'H4010A': "#a1d99b",
    'H4030': "#6ba368",
    'H5130': "#9467bd",
    'H6120': "#dbc33b",
    'H6230': "#d6e642",
    'H6410': "#e377c2",
    'H6430A': "#0c5a92",
    'H6430B': "#0c5a92",
    'H6430C': "#6a9775",
    'H6510A': "#aabb6e",
    'H6510B': "#aabb6e",
    'H7110A': "#329e32",
    'H7110B': "#329e32",
    'H7120': "#4cd64c",
    'H7140A': "#40cfc1",
    'H7150': "#ffd59a",
    'H7210': "#0c5a92",
    'H7230': "#ffb347",
    'H9160A': "#41bd5e",
    'H9190': "#cb8d6a",
    'H91D0': "#266d36",
    'H91E0A': "#aec7e8",
    'H91E0B': "#aec7e8",
    'H91E0C': "#aec7e8",
    'H91F0': "#bcbd22",
    'H9120': "#cb8d6a",
    'LGN_OW': "#0c5a92"
}

habitat_reference__WD__df['habitat_color'] = (
    habitat_reference__WD__df.index.to_series()
    .map(all_habitat_color_list)        
    .fillna("#000000")              
)

In [6]:
# Adding WD-division to the habitat_reference__WD__df
habitat_WD_division = {
    # Wet Nature
    'H3130': 'Wet Nature',
    'H3160': 'Wet Nature',
    'H6410': 'Wet Nature',
    'H7110A': 'Wet Nature',
    'H7110B': 'Wet Nature',
    'H7120': 'Wet Nature',
    'H7140A': 'Wet Nature',
    'H7230': 'Wet Nature',

    # Semi-Wet Nature
    'H91D0': 'Semi-Wet Nature',
    'H91E0A': 'Semi-Wet Nature',
    'H91E0B': 'Semi-Wet Nature',
    'H91E0C': 'Semi-Wet Nature',
    'H3270': 'Semi-Wet Nature',
    'H4010A': 'Semi-Wet Nature',
    'H6430A': 'Semi-Wet Nature',
    'H6430B': 'Semi-Wet Nature',
    'H6510B': 'Semi-Wet Nature',
    'H7150': 'Semi-Wet Nature',
    'H9160A': 'Semi-Wet Nature',

    # Dry Nature
    'H91F0': 'Dry Nature',
    'H2310': 'Dry Nature',
    'H2320': 'Dry Nature',
    'H2330': 'Dry Nature',
    'H4030': 'Dry Nature',
    'H5130': 'Dry Nature',
    'H6120': 'Dry Nature',
    'H6230': 'Dry Nature',
    'H6430C': 'Dry Nature',
    'H6510A': 'Dry Nature',
    'H9120': 'Dry Nature',
    'H9190': 'Dry Nature',

    # Open water
    'H3150': 'Open water',
    'H3260A': 'Open water',
    'H3260B': 'Open water',
    'H7210': 'Open water',
    'LGN_OW': 'Open water',

    # No-Habitat
    'H0000': 'No-Habitat',
}

habitat_reference__WD__df['WD_division'] = habitat_reference__WD__df.index.map(habitat_WD_division)

In [7]:
# Adding WD1-division to the habitat_reference__HB__df
habitat_WD1_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3150": "Open water",

    # Wet Nature
    "H3130": "Wet Nature",
    "H3160": "Wet Nature",
    "H3270": "Wet Nature",
    "H4010A": "Wet Nature",
    "H6410": "Wet Nature",
    "H6510B": "Wet Nature",
    "H7110A": "Wet Nature",
    "H7110B": "Wet Nature",
    "H7120": "Wet Nature",
    "H7140A": "Wet Nature",
    "H7150": "Wet Nature",
    "H7210": "Wet Nature",
    "H7230": "Wet Nature",
    "H91D0": "Wet Nature",
    'H91E0A': "Wet Nature",
    'H91E0B': "Wet Nature",
    'H91E0C': "Wet Nature",

    # Remaining
    "H0000": "Remaining",
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",
}

habitat_reference__WD__df['WD1_division'] = habitat_reference__WD__df.index.map(habitat_WD1_division)

In [8]:
# Adding WD2-division to the habitat_reference__HB__df
habitat_WD2_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3150": "Open water",

    # Wet Nature
    "H3130": "Wet Nature",
    "H3160": "Wet Nature",
    "H3270": "Wet Nature",
    "H4010A": "Wet Nature",
    "H6410": "Wet Nature",
    "H6510B": "Wet Nature",
    "H7110A": "Wet Nature",
    "H7110B": "Wet Nature",
    "H7120": "Wet Nature",
    "H7140A": "Wet Nature",
    "H7150": "Wet Nature",
    "H7210": "Wet Nature",
    "H7230": "Wet Nature",
    "H91D0": "Wet Nature",
    'H91E0A': "Wet Nature",
    'H91E0B': "Wet Nature",
    'H91E0C': "Wet Nature",

    # Remaining
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",

    # Removed
    # "H0000": "[x]",
}

habitat_reference__WD__df['WD2_division'] = habitat_reference__WD__df.index.map(habitat_WD2_division)

In [9]:
# WD3-division mapping 
habitat_WD3_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3150": "Open water",

    # Wet Nature
    "H3130": "Wet Nature",
    "H3160": "Wet Nature",
    "H7210": "Wet Nature",

    # Semi-Wet Nature
    "H3270": "Semi-Wet Nature",
    "H4010A": "Semi-Wet Nature",
    "H6410": "Semi-Wet Nature",
    "H6510B": "Semi-Wet Nature",
    "H7110A": "Semi-Wet Nature",
    "H7110B": "Semi-Wet Nature",
    "H7120": "Semi-Wet Nature",
    "H7140A": "Semi-Wet Nature",
    "H7150": "Semi-Wet Nature",
    "H7230": "Semi-Wet Nature",
    "H91D0": "Semi-Wet Nature",
    'H91E0A': "Semi-Wet Nature",
    'H91E0B': "Semi-Wet Nature",
    'H91E0C': "Semi-Wet Nature",

    # Remaining
    "H0000": "Remaining",
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",
}

habitat_reference__WD__df['WD3_division'] = habitat_reference__WD__df.index.map(habitat_WD3_division)

In [10]:
# WD4-division mapping 
habitat_WD4_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3150": "Open water",

    # Wet Nature
    "H3130": "Wet Nature",
    "H3160": "Wet Nature",
    "H7210": "Wet Nature",

    # Semi-Wet Nature
    "H3270": "Semi-Wet Nature",
    "H4010A": "Semi-Wet Nature",
    "H6410": "Semi-Wet Nature",
    "H6510B": "Semi-Wet Nature",
    "H7110A": "Semi-Wet Nature",
    "H7110B": "Semi-Wet Nature",
    "H7120": "Semi-Wet Nature",
    "H7140A": "Semi-Wet Nature",
    "H7150": "Semi-Wet Nature",
    "H7230": "Semi-Wet Nature",
    "H91D0": "Semi-Wet Nature",
    'H91E0A': "Semi-Wet Nature",
    'H91E0B': "Semi-Wet Nature",
    'H91E0C': "Semi-Wet Nature",

    # Remaining
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",

    # Removed
    # "H0000": "[x]",
}

habitat_reference__WD__df['WD4_division'] = habitat_reference__WD__df.index.map(habitat_WD4_division)

In [11]:
# Adding WD5-division to the habitat_reference__HB__df
habitat_WD5_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3130": "Open water",
    "H3150": "Open water",
    "H3160": "Open water",
    "H3270": "Open water",
    "H7120": "Open water",

    # Semi-Wet Nature
    "H4010A": "Semi-Wet Nature",
    "H6410": "Semi-Wet Nature",
    "H6510B": "Semi-Wet Nature",
    "H7110A": "Semi-Wet Nature",
    "H7110B": "Semi-Wet Nature",
    "H7140A": "Semi-Wet Nature",
    "H7150": "Semi-Wet Nature",
    "H7210": "Semi-Wet Nature",
    "H7230": "Semi-Wet Nature",
    "H91D0": "Semi-Wet Nature",
    'H91E0A': "Semi-Wet Nature",
    'H91E0B': "Semi-Wet Nature",
    'H91E0C': "Semi-Wet Nature",

    # Remaining
    "H0000": "Remaining",
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",
}

habitat_reference__WD__df['WD5_division'] = habitat_reference__WD__df.index.map(habitat_WD5_division)

In [12]:
# Adding WD6-division to the habitat_reference__HB__df
habitat_WD6_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3130": "Open water",
    "H3150": "Open water",
    "H3160": "Open water",
    "H3270": "Open water",
    "H7120": "Open water",

    # Semi-Wet Nature
    "H4010A": "Semi-Wet Nature",
    "H6410": "Semi-Wet Nature",
    "H6510B": "Semi-Wet Nature",
    "H7110A": "Semi-Wet Nature",
    "H7110B": "Semi-Wet Nature",
    "H7140A": "Semi-Wet Nature",
    "H7150": "Semi-Wet Nature",
    "H7210": "Semi-Wet Nature",
    "H7230": "Semi-Wet Nature",
    "H91D0": "Semi-Wet Nature",
    'H91E0A': "Semi-Wet Nature",
    'H91E0B': "Semi-Wet Nature",
    'H91E0C': "Semi-Wet Nature",

    # Remaining
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",

    # Removed
    # "H0000": "[x]",
}

habitat_reference__WD__df['WD6_division'] = habitat_reference__WD__df.index.map(habitat_WD6_division)

In [13]:
# Adding WD-division colors
WD_color_map = {
    "Open water": "#003f69",
    "Wet Nature": "#329e32",
    "Semi-Wet Nature": "#3E8F8B",
    "Dry Nature": "#ffff99",
    "No-Habitat": "#f54949",
    "Remaining": "#aaaaaa",
}

habitat_reference__WD__df['WD_color'] = habitat_reference__WD__df['WD_division'].map(WD_color_map)
habitat_reference__WD__df['WD1_color'] = habitat_reference__WD__df['WD1_division'].map(WD_color_map)
habitat_reference__WD__df['WD2_color'] = habitat_reference__WD__df['WD2_division'].map(WD_color_map)
habitat_reference__WD__df['WD3_color'] = habitat_reference__WD__df['WD3_division'].map(WD_color_map)
habitat_reference__WD__df['WD4_color'] = habitat_reference__WD__df['WD4_division'].map(WD_color_map)
habitat_reference__WD__df['WD5_color'] = habitat_reference__WD__df['WD5_division'].map(WD_color_map)
habitat_reference__WD__df['WD6_color'] = habitat_reference__WD__df['WD6_division'].map(WD_color_map)

In [14]:
habitat_reference__WD__df.columns

Index(['habitatnaam_disp', 'habitat_color', 'WD_division', 'WD1_division',
       'WD2_division', 'WD3_division', 'WD4_division', 'WD5_division',
       'WD6_division', 'WD_color', 'WD1_color', 'WD2_color', 'WD3_color',
       'WD4_color', 'WD5_color', 'WD6_color'],
      dtype='object')

In [15]:
WD_column_order = ['habitatnaam_disp', 'habitat_color', 'WD_division', 'WD_color', 'WD1_division',
       'WD1_color', 'WD2_division',  'WD2_color', 'WD3_division', 'WD3_color', 'WD4_division', 'WD4_color',
       'WD5_division', 'WD5_color', 'WD6_division', 'WD6_color']

habitat_reference__WD__df = habitat_reference__WD__df[WD_column_order]

In [16]:
habitat_reference__WD__df.head()

,habitatnaam_disp,habitat_color,WD_division,WD_color,WD1_division,WD1_color,WD2_division,WD2_color,WD3_division,WD3_color,WD4_division,WD4_color,WD5_division,WD5_color,WD6_division,WD6_color
habitatType,,,,,,,,,,,,,,,,
H0000,Geen habitattype,#999999,No-Habitat,#f54949,Remaining,#aaaaaa,NaN,NaN,Remaining,#aaaaaa,NaN,NaN,Remaining,#aaaaaa,NaN,NaN
H2310,Stuifzandheiden met struikhei,#fff7b2,Dry Nature,#ffff99,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H2320,Binnenlandse kraaheibegroeiingen,#8c564b,Dry Nature,#ffff99,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H2330,Zandverstuivingen,#e8d6c3,Dry Nature,#ffff99,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H3130,Zwakgebufferde vennen,#9ed6f8,Wet Nature,#329e32,Wet Nature,#329e32,Wet Nature,#329e32,Wet Nature,#329e32,Wet Nature,#329e32,Open water,#003f69,Open water,#003f69

In [17]:
habitat_reference__WD__df.to_pickle(habitat_reference__WD__df_path)

## Habitat Reference s-division df

In [18]:
# Building the s grouping df
habitat_reference__s__df = pd.DataFrame(
    list(short_habitat_names.items()),
    columns=["habitatType", "habitatnaam_disp"]
)

habitat_reference__s__df = habitat_reference__s__df.set_index("habitatType")

In [19]:
# Adding color
habitat_reference__s__df['habitat_color'] = (
    habitat_reference__s__df.index.to_series()
    .map(all_habitat_color_list)        
    .fillna("#000000")              
)

In [20]:
habitat_s1_division = {
    # s1 division of interest
    "H3130": "Zwakgebufferde vennen",
    "H3160": "Zure vennen",
    "H4010A": "Vochtige heiden",
    "H7110B": "Actieve hoogvenen (heideveentjes)",
    "H7140A": "Overgangs- & trilven",
    'LGN_OW': 'Open water',

    # Remaining
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H3150": "Remaining",
    "H3260A": "Remaining",
    "H3260B": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6410": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H7110A": "Remaining",
    "H7120": "Remaining",
    "H7150": "Remaining",
    "H7230": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H91F0": "Remaining",

    # [X]
    # "H0000": "No-Habitat",
    # "H3270": "[X]",
    # "H9190": "[X]",
    # "H91D0": "[X]",
    # "H91E0A": "[X]",
    # "H91E0B": "[X]",
    # "H91E0C": "[X]",
}

habitat_reference__s__df['s1_division'] = habitat_reference__s__df.index.map(habitat_s1_division)

In [21]:
habitat_s2_division = {
    # s2-selection
    'H3130': 'Ven',
    'H3160': 'Ven',
    'H4010A': 'Vochtige heiden',
    'H7110B': 'Actieve hoogvenen (heideveentjes)',
    'H7140A': 'Ven',
    'LGN_OW': 'Open water',

    # Remaining
    'H2310': 'Remaining',
    'H2320': 'Remaining',
    'H2330': 'Remaining',
    'H3150': 'Remaining',
    'H3260A': 'Remaining',
    'H3260B': 'Remaining',
    'H4030': 'Remaining',
    'H5130': 'Remaining',
    'H6120': 'Remaining',
    'H6230': 'Remaining',
    'H6410': 'Remaining',
    'H6430A': 'Remaining',
    'H6430B': 'Remaining',
    'H6430C': 'Remaining',
    'H7110A': 'Remaining',
    'H7120': 'Remaining',
    'H7150': 'Remaining',
    'H7230': 'Remaining',
    'H9120': 'Remaining',
    'H9160A': 'Remaining',
    'H9190': 'Remaining',
    'H91F0': 'Remaining',

    # [X]
    # 'H0000': 'Geen habitattype',
    # 'H3270': 'slikkige rivieroevers',
    # 'H6510A': 'Glanshaver',
    # 'H6510B': 'Grote Vossenstaart',
    # 'H7210': 'Galigaanmoerassen',
    # 'H91D0': 'Hoogveenbossen',
    # 'H91E0A': 'Vochtige alluviale bossen zachthoutooi',
    # 'H91E0B': 'Vochtige alluviale bossen essen-iep',
    # 'H91E0C': 'Vochtige alluviale bossen beenbreek',
}

habitat_reference__s__df['s2_division'] = habitat_reference__s__df.index.map(habitat_s2_division)

In [22]:
habitat_s3_division = {
    # s3-selection
    'H3130': 'Ven',
    'H3160': 'Ven',
    'H4010A': 'Vochtige heiden',
    'H7110B': 'Actieve hoogvenen (heideveentjes)',
    'LGN_OW': 'Open water',

    # Remaining
    'H2310': 'Remaining',
    'H2320': 'Remaining',
    'H2330': 'Remaining',
    'H3150': 'Remaining',
    'H3260A': 'Remaining',
    'H3260B': 'Remaining',
    'H4030': 'Remaining',
    'H5130': 'Remaining',
    'H6120': 'Remaining',
    'H6230': 'Remaining',
    'H6410': 'Remaining',
    'H6430A': 'Remaining',
    'H6430B': 'Remaining',
    'H6430C': 'Remaining',
    'H7110A': 'Remaining',
    'H7120': 'Remaining',
    'H7140A': 'Remaining',
    'H7150': 'Remaining',
    'H7230': 'Remaining',
    'H9120': 'Remaining',
    'H9160A': 'Remaining',
    'H9190': 'Remaining',
    'H91F0': 'Remaining',

    # [X]
    # 'H0000': 'Geen habitattype',
    # 'H3270': 'slikkige rivieroevers',
    # 'H6510A': 'Glanshaver',
    # 'H6510B': 'Grote Vossenstaart',
    # 'H7210': 'Galigaanmoerassen',
    # 'H91D0': 'Hoogveenbossen',
    # 'H91E0A': 'Vochtige alluviale bossen zachthoutooi',
    # 'H91E0B': 'Vochtige alluviale bossen essen-iep',
    # 'H91E0C': 'Vochtige alluviale bossen beenbreek',
}

habitat_reference__s__df['s3_division'] = habitat_reference__s__df.index.map(habitat_s3_division)

In [23]:
s_color_map = {
    "Open water": "#003f69",
    'Ven': "#2e86c1",
    "Zwakgebufferde vennen": "#9ed6f8",
    "Zure vennen": "#2e86c1",
    "Vochtige heiden": "#a1d99b",
    "Actieve hoogvenen (heideveentjes)": "#329e32",
    "Overgangs- & trilven": "#40cfc1",
    "No-Habitat": "#f54949",
    "Remaining": "#aaaaaa",
}

In [24]:
habitat_reference__s__df['s1_color'] = habitat_reference__s__df['s1_division'].map(s_color_map)
habitat_reference__s__df['s2_color'] = habitat_reference__s__df['s2_division'].map(s_color_map)
habitat_reference__s__df['s3_color'] = habitat_reference__s__df['s3_division'].map(s_color_map)

In [25]:
habitat_reference__s__df.head()

,habitatnaam_disp,habitat_color,s1_division,s2_division,s3_division,s1_color,s2_color,s3_color
habitatType,,,,,,,,
H0000,Geen habitattype,#999999,NaN,NaN,NaN,NaN,NaN,NaN
H2310,Stuifzandheiden met struikhei,#fff7b2,Remaining,Remaining,Remaining,#aaaaaa,#aaaaaa,#aaaaaa
H2320,Binnenlandse kraaheibegroeiingen,#8c564b,Remaining,Remaining,Remaining,#aaaaaa,#aaaaaa,#aaaaaa
H2330,Zandverstuivingen,#e8d6c3,Remaining,Remaining,Remaining,#aaaaaa,#aaaaaa,#aaaaaa
H3130,Zwakgebufferde vennen,#9ed6f8,Zwakgebufferde vennen,Ven,Ven,#9ed6f8,#2e86c1,#2e86c1

In [26]:
s_column_order = ['habitatnaam_disp', 'habitat_color', 's1_division', 's1_color', 's2_division', 's2_color', 's3_division', 's3_color']

habitat_reference__s__df = habitat_reference__s__df[s_column_order]

In [27]:
habitat_reference__s__df.to_pickle(habitat_reference__s__df_path)

In [28]:
habitat_reference__s__df

,habitatnaam_disp,habitat_color,s1_division,s1_color,s2_division,s2_color,s3_division,s3_color
habitatType,,,,,,,,
H0000,Geen habitattype,#999999,NaN,NaN,NaN,NaN,NaN,NaN
H2310,Stuifzandheiden met struikhei,#fff7b2,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H2320,Binnenlandse kraaheibegroeiingen,#8c564b,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H2330,Zandverstuivingen,#e8d6c3,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H3130,Zwakgebufferde vennen,#9ed6f8,Zwakgebufferde vennen,#9ed6f8,Ven,#2e86c1,Ven,#2e86c1
H3150,Meren krabbenscheer & fonteinkruiden,#00375f,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H3160,Zure vennen,#2e86c1,Zure vennen,#2e86c1,Ven,#2e86c1,Ven,#2e86c1
H3260A,Beken & rivieren met waterplanten,#0c5a92,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H3260B,Beken & rivieren met waterplanten,#0c5a92,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H3270,slikkige rivieroevers,#9b4f12,NaN,NaN,NaN,NaN,NaN,NaN
H4010A,Vochtige heiden,#a1d99b,Vochtige heiden,#a1d99b,Vochtige heiden,#a1d99b,Vochtige heiden,#a1d99b
H4030,Droge heiden,#6ba368,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H5130,Jeneverbesstruwelen,#9467bd,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H6120,Stroomdalgraslanden,#dbc33b,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H6230,Heischrale graslanden,#d6e642,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H6410,Blauwgraslanden,#e377c2,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H6430A,moerasspirea,#0c5a92,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H6430B,Ruigten en zomen (harig wilgenroosje),#0c5a92,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H6430C,Droge bosranden,#6a9775,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H6510A,Glanshaver,#aabb6e,NaN,NaN,NaN,NaN,NaN,NaN
H6510B,Grote Vossenstaart,#aabb6e,NaN,NaN,NaN,NaN,NaN,NaN
H7110A,Actieve hoogvenen (hoogveenlandschap),#329e32,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H7110B,Actieve hoogvenen (heideveentjes),#329e32,Actieve hoogvenen (heideveentjes),#329e32,Actieve hoogvenen (heideveentjes),#329e32,Actieve hoogvenen (heideveentjes),#329e32
H7120,Herstellend hoogveen,#4cd64c,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H7140A,Overgangs- & trilven,#40cfc1,Overgangs- & trilven,#40cfc1,Ven,#2e86c1,Remaining,#aaaaaa
H7150,Pionierveg met snavelbies,#ffd59a,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H7210,Galigaanmoerassen,#0c5a92,NaN,NaN,NaN,NaN,NaN,NaN
H7230,Kalkmoerassen,#ffb347,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H9120,Beuken-eikenbossen,#cb8d6a,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H9160A,Eiken-haagbeukenbossen,#41bd5e,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H9190,Oude eikenbossen,#cb8d6a,NaN,NaN,Remaining,#aaaaaa,Remaining,#aaaaaa
H91D0,Hoogveenbossen,#266d36,NaN,NaN,NaN,NaN,NaN,NaN
H91E0A,Vochtige alluviale bossen zachthoutooi,#aec7e8,NaN,NaN,NaN,NaN,NaN,NaN
H91E0B,Vochtige alluviale bossen essen-iep,#aec7e8,NaN,NaN,NaN,NaN,NaN,NaN
H91E0C,Vochtige alluviale bossen beenbreek,#aec7e8,NaN,NaN,NaN,NaN,NaN,NaN
H91F0,Droge hardhoutooibossen,#bcbd22,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
LGN_OW,Open water,#0c5a92,Open water,#003f69,Open water,#003f69,Open water,#003f69

## Habitat Reference WDNF

Changing Hab map, means changing classes in NB03_building_entropy_rasters!

In [29]:
# Linking habitat code to the display name
habitat_reference__WDNF__df = pd.DataFrame(
    list(short_habitat_names.items()),
    columns=["habitatType", "habitatnaam_disp"]
)

habitat_reference__WDNF__df = habitat_reference__WDNF__df.set_index("habitatType")

In [30]:
# Adding color to the habitat_reference__WDNF__df

habitat_reference__WDNF__df['habitat_color'] = (
    habitat_reference__WDNF__df.index.to_series()
    .map(all_habitat_color_list)        
    .fillna("#000000")              
)

In [31]:
# Adding WDNF1-division to the habitat_reference__WD__df
habitat_WDNF1_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3150": "Open water",

    # Wet Nature
    "H3130": "Wet Nature",
    "H3160": "Wet Nature",
    "H4010A": "Wet Nature",
    "H6410": "Wet Nature",
    "H6510B": "Wet Nature",
    "H7110A": "Wet Nature",
    "H7110B": "Wet Nature",
    "H7120": "Wet Nature",
    "H7140A": "Wet Nature",
    "H7150": "Wet Nature",
    "H7230": "Wet Nature",
    "H91D0": "Wet Nature",

    # Remaining
    "H0000": "Remaining",
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",

    # Removed
    # "H3270": "[x]",
    # "H7210": "[x]",
    # 'H91E0A': "[x]",
    # 'H91E0B': "[x]",
    # 'H91E0C': "[x]",
}

habitat_reference__WDNF__df['WDNF1_division'] = habitat_reference__WDNF__df.index.map(habitat_WDNF1_division)

In [32]:
# Adding WDNF2-division to the habitat_reference__HB__df
habitat_WDNF2_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3150": "Open water",

    # Wet Nature
    "H3130": "Wet Nature",
    "H3160": "Wet Nature",
    "H4010A": "Wet Nature",
    "H6410": "Wet Nature",
    "H6510B": "Wet Nature",
    "H7110A": "Wet Nature",
    "H7110B": "Wet Nature",
    "H7120": "Wet Nature",
    "H7140A": "Wet Nature",
    "H7150": "Wet Nature",
    "H7230": "Wet Nature",
    "H91D0": "Wet Nature",

    # Remaining
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",

    # Removed
    # "H0000": "[x]",
    # "H3270": "[x]",
    # "H7210": "[x]",
    # 'H91E0A': "[x]",
    # 'H91E0B': "[x]",
    # 'H91E0C': "[x]",
}

habitat_reference__WDNF__df['WDNF2_division'] = habitat_reference__WDNF__df.index.map(habitat_WDNF2_division)

In [33]:
# WDNF3-division mapping 
habitat_WDNF3_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3150": "Open water",

    # Wet Nature
    "H3130": "Wet Nature",
    "H3160": "Wet Nature",

    # Semi-Wet Nature
    "H4010A": "Semi-Wet Nature",
    "H6410": "Semi-Wet Nature",
    "H6510B": "Semi-Wet Nature",
    "H7110A": "Semi-Wet Nature",
    "H7110B": "Semi-Wet Nature",
    "H7120": "Semi-Wet Nature",
    "H7140A": "Semi-Wet Nature",
    "H7150": "Semi-Wet Nature",
    "H7230": "Semi-Wet Nature",
    "H91D0": "Semi-Wet Nature",

    # Remaining
    "H0000": "Remaining",
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",

    # Removed
    # "H3270": "[x]",
    # "H7210": "[x]",
    # 'H91E0A': "[x]",
    # 'H91E0B': "[x]",
    # 'H91E0C': "[x]",
}

habitat_reference__WDNF__df['WDNF3_division'] = habitat_reference__WDNF__df.index.map(habitat_WDNF3_division)

In [34]:
# WDNF4-division mapping 
habitat_WDNF4_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3150": "Open water",

    # Wet Nature
    "H3130": "Wet Nature",
    "H3160": "Wet Nature",

    # Semi-Wet Nature
    "H4010A": "Semi-Wet Nature",
    "H6410": "Semi-Wet Nature",
    "H6510B": "Semi-Wet Nature",
    "H7110A": "Semi-Wet Nature",
    "H7110B": "Semi-Wet Nature",
    "H7120": "Semi-Wet Nature",
    "H7140A": "Semi-Wet Nature",
    "H7150": "Semi-Wet Nature",
    "H7230": "Semi-Wet Nature",
    "H91D0": "Semi-Wet Nature",

    # Remaining
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",

    # Removed
    # "H0000": "[x]",
    # "H3270": "[x]",
    # "H7210": "[x]",
    # 'H91E0A': "[x]",
    # 'H91E0B': "[x]",
    # 'H91E0C': "[x]",
}

habitat_reference__WDNF__df['WDNF4_division'] = habitat_reference__WDNF__df.index.map(habitat_WDNF4_division)

In [35]:
# Adding WDNF5-division to the habitat_reference__WD__df
habitat_WDNF5_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3130": "Open water",
    "H3150": "Open water",
    "H3160": "Open water",
    "H7120": "Open water",

    # Semi-Wet Nature
    "H4010A": "Semi-Wet Nature",
    "H6410": "Semi-Wet Nature",
    "H6510B": "Semi-Wet Nature",
    "H7110A": "Semi-Wet Nature",
    "H7110B": "Semi-Wet Nature",
    "H7140A": "Semi-Wet Nature",
    "H7150": "Semi-Wet Nature",
    "H7230": "Semi-Wet Nature",
    "H91D0": "Semi-Wet Nature",

    # Remaining
    "H0000": "Remaining",
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",

    # Removed
    # "H3270": "[x]",
    # "H7210": "[x]",
    # 'H91E0A': "[x]",
    # 'H91E0B': "[x]",
    # 'H91E0C': "[x]",
}

habitat_reference__WDNF__df['WDNF5_division'] = habitat_reference__WDNF__df.index.map(habitat_WDNF5_division)

In [36]:
# Adding WDNF6-division to the habitat_reference__HB__df
habitat_WDNF6_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3130": "Open water",
    "H3150": "Open water",
    "H3160": "Open water",
    "H7120": "Open water",

    # Semi-Wet Nature
    "H4010A": "Semi-Wet Nature",
    "H6410": "Semi-Wet Nature",
    "H6510B": "Semi-Wet Nature",
    "H7110A": "Semi-Wet Nature",
    "H7110B": "Semi-Wet Nature",
    "H7140A": "Semi-Wet Nature",
    "H7150": "Semi-Wet Nature",
    "H7230": "Semi-Wet Nature",
    "H91D0": "Semi-Wet Nature",

    # Remaining
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",

    # Removed
    # "H0000": "[x]",
    # "H3270": "[x]",
    # "H7210": "[x]",
    # 'H91E0A': "[x]",
    # 'H91E0B': "[x]",
    # 'H91E0C': "[x]",
}

habitat_reference__WDNF__df['WDNF6_division'] = habitat_reference__WDNF__df.index.map(habitat_WDNF6_division)

In [37]:
# Adding WDNF-division colors
WDNF_color_map = {
    "Open water": "#003f69",
    "Wet Nature": "#329e32",
    "Semi-Wet Nature": "#3E8F8B",
    "Dry Nature": "#ffff99",
    "No-Habitat": "#f54949",
    "Remaining": "#aaaaaa",
}

habitat_reference__WDNF__df['WDNF1_color'] = habitat_reference__WDNF__df['WDNF1_division'].map(WDNF_color_map)
habitat_reference__WDNF__df['WDNF2_color'] = habitat_reference__WDNF__df['WDNF2_division'].map(WDNF_color_map)
habitat_reference__WDNF__df['WDNF3_color'] = habitat_reference__WDNF__df['WDNF3_division'].map(WDNF_color_map)
habitat_reference__WDNF__df['WDNF4_color'] = habitat_reference__WDNF__df['WDNF4_division'].map(WDNF_color_map)
habitat_reference__WDNF__df['WDNF5_color'] = habitat_reference__WDNF__df['WDNF5_division'].map(WDNF_color_map)
habitat_reference__WDNF__df['WDNF6_color'] = habitat_reference__WDNF__df['WDNF6_division'].map(WDNF_color_map)

In [38]:
habitat_reference__WDNF__df.columns

Index(['habitatnaam_disp', 'habitat_color', 'WDNF1_division', 'WDNF2_division',
       'WDNF3_division', 'WDNF4_division', 'WDNF5_division', 'WDNF6_division',
       'WDNF1_color', 'WDNF2_color', 'WDNF3_color', 'WDNF4_color',
       'WDNF5_color', 'WDNF6_color'],
      dtype='object')

In [39]:
WDNF_column_order = ['habitatnaam_disp', 'habitat_color', 'WDNF1_division', 'WDNF1_color', 'WDNF2_division',  
       'WDNF2_color', 'WDNF3_division', 'WDNF3_color', 'WDNF4_division', 'WDNF4_color', 'WDNF5_division', 
       'WDNF5_color', 'WDNF6_division', 'WDNF6_color'
]

habitat_reference__WDNF__df = habitat_reference__WDNF__df[WDNF_column_order]

In [40]:
habitat_reference__WDNF__df.head()

,habitatnaam_disp,habitat_color,WDNF1_division,WDNF1_color,WDNF2_division,WDNF2_color,WDNF3_division,WDNF3_color,WDNF4_division,WDNF4_color,WDNF5_division,WDNF5_color,WDNF6_division,WDNF6_color
habitatType,,,,,,,,,,,,,,
H0000,Geen habitattype,#999999,Remaining,#aaaaaa,NaN,NaN,Remaining,#aaaaaa,NaN,NaN,Remaining,#aaaaaa,NaN,NaN
H2310,Stuifzandheiden met struikhei,#fff7b2,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H2320,Binnenlandse kraaheibegroeiingen,#8c564b,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H2330,Zandverstuivingen,#e8d6c3,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H3130,Zwakgebufferde vennen,#9ed6f8,Wet Nature,#329e32,Wet Nature,#329e32,Wet Nature,#329e32,Wet Nature,#329e32,Open water,#003f69,Open water,#003f69

In [41]:
habitat_reference__WDNF__df.to_pickle(habitat_reference__WDNF__df_path)

# Habtat Reference UC (Unsupervised Clustering)

In [42]:
# Building the UC grouping df
habitat_reference__UC__df = pd.DataFrame(
    list(short_habitat_names.items()),
    columns=["habitatType", "habitatnaam_disp"]
)

habitat_reference__UC__df = habitat_reference__UC__df.set_index("habitatType")
# Adding color
habitat_reference__UC__df['habitat_color'] = (
    habitat_reference__UC__df.index.to_series()
    .map(all_habitat_color_list)        
    .fillna("#000000")              
)

In [43]:
# Adding WD1-division to the habitat_reference__HB__df
habitat_UC1_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3150": "Open water",

    # Wet Nature
    "H3130": "Wet Nature",
    "H3160": "Wet Nature",
    "H3270": "Wet Nature",
    "H4010A": "Wet Nature",
    "H6410": "Wet Nature",
    "H6510B": "Wet Nature",
    "H7110A": "Wet Nature",
    "H7110B": "Wet Nature",
    "H7120": "Wet Nature",
    "H7140A": "Wet Nature",
    "H7150": "Wet Nature",
    "H7210": "Wet Nature",
    "H7230": "Wet Nature",
    "H91D0": "Wet Nature",
    'H91E0A': "Wet Nature",
    'H91E0B': "Wet Nature",
    'H91E0C': "Wet Nature",

    # Remaining
    "H0000": "Remaining",
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",
}

habitat_reference__UC__df['UC1_division'] = habitat_reference__UC__df.index.map(habitat_UC1_division)

In [44]:
# UC3-division mapping 
habitat_UC3_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3150": "Open water",

    # Wet Nature
    "H3130": "Wet Nature",
    "H3160": "Wet Nature",
    "H7210": "Wet Nature",

    # Semi-Wet Nature
    "H3270": "Semi-Wet Nature",
    "H4010A": "Semi-Wet Nature",
    "H6410": "Semi-Wet Nature",
    "H6510B": "Semi-Wet Nature",
    "H7110A": "Semi-Wet Nature",
    "H7110B": "Semi-Wet Nature",
    "H7120": "Semi-Wet Nature",
    "H7140A": "Semi-Wet Nature",
    "H7150": "Semi-Wet Nature",
    "H7230": "Semi-Wet Nature",
    "H91D0": "Semi-Wet Nature",
    'H91E0A': "Semi-Wet Nature",
    'H91E0B': "Semi-Wet Nature",
    'H91E0C': "Semi-Wet Nature",

    # Remaining
    "H0000": "Remaining",
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",
}

habitat_reference__UC__df['UC3_division'] = habitat_reference__UC__df.index.map(habitat_UC3_division)

In [45]:
# Adding UC5-division to the habitat_reference__HB__df
habitat_UC5_division = {
    # Open water
    'LGN_OW': 'Open water',
    "H3260A": "Open water",
    "H3260B": "Open water",
    "H3130": "Open water",
    "H3150": "Open water",
    "H3160": "Open water",
    "H3270": "Open water",
    "H7120": "Open water",

    # Semi-Wet Nature
    "H4010A": "Semi-Wet Nature",
    "H6410": "Semi-Wet Nature",
    "H6510B": "Semi-Wet Nature",
    "H7110A": "Semi-Wet Nature",
    "H7110B": "Semi-Wet Nature",
    "H7140A": "Semi-Wet Nature",
    "H7150": "Semi-Wet Nature",
    "H7210": "Semi-Wet Nature",
    "H7230": "Semi-Wet Nature",
    "H91D0": "Semi-Wet Nature",
    'H91E0A': "Semi-Wet Nature",
    'H91E0B': "Semi-Wet Nature",
    'H91E0C': "Semi-Wet Nature",

    # Remaining
    "H0000": "Remaining",
    "H2310": "Remaining",
    "H2320": "Remaining",
    "H2330": "Remaining",
    "H4030": "Remaining",
    "H5130": "Remaining",
    "H6120": "Remaining",
    "H6230": "Remaining",
    "H6430A": "Remaining",
    "H6430B": "Remaining",
    "H6430C": "Remaining",
    "H6510A": "Remaining",
    "H9120": "Remaining",
    "H9160A": "Remaining",
    "H9190": "Remaining",
    "H91F0": "Remaining",
}

habitat_reference__UC__df['UC5_division'] = habitat_reference__UC__df.index.map(habitat_UC5_division)

In [46]:
# Adding WD-division colors
UC_color_map = {
    "Open water": "#003f69",
    "Wet Nature": "#329e32",
    "Semi-Wet Nature": "#3E8F8B",
    "Dry Nature": "#ffff99",
    "No-Habitat": "#f54949",
    "Remaining": "#aaaaaa",
}

habitat_reference__UC__df['UC1_color'] = habitat_reference__UC__df['UC1_division'].map(UC_color_map)
habitat_reference__UC__df['UC3_color'] = habitat_reference__UC__df['UC3_division'].map(UC_color_map)
habitat_reference__UC__df['UC5_color'] = habitat_reference__UC__df['UC5_division'].map(UC_color_map)

In [47]:
habitat_reference__UC__df.columns

Index(['habitatnaam_disp', 'habitat_color', 'UC1_division', 'UC3_division',
       'UC5_division', 'UC1_color', 'UC3_color', 'UC5_color'],
      dtype='object')

In [48]:
UC_column_order = ['habitatnaam_disp', 'habitat_color', 'UC1_division',
       'UC1_color', 'UC3_division', 'UC3_color',
       'UC5_division', 'UC5_color']

habitat_reference__UC__df = habitat_reference__UC__df[UC_column_order]

In [49]:
habitat_reference__UC__df.to_pickle(habitat_reference__UC__df_path)

In [50]:
habitat_reference__UC__df.head()

,habitatnaam_disp,habitat_color,UC1_division,UC1_color,UC3_division,UC3_color,UC5_division,UC5_color
habitatType,,,,,,,,
H0000,Geen habitattype,#999999,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H2310,Stuifzandheiden met struikhei,#fff7b2,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H2320,Binnenlandse kraaheibegroeiingen,#8c564b,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H2330,Zandverstuivingen,#e8d6c3,Remaining,#aaaaaa,Remaining,#aaaaaa,Remaining,#aaaaaa
H3130,Zwakgebufferde vennen,#9ed6f8,Wet Nature,#329e32,Wet Nature,#329e32,Open water,#003f69

End of the Notebook