_In the last Notebook (n05_pixelize_hab_kart), the FC p80 tmp2 was pixelized. Using QGIS all pixels were visually checked. This notebook imports the manually selected pixeled GPKG and builds new IDX dfs for the training/validation split._ <br>

_As the Gelderland Habitat kart has been the most reliable so far, this is the only GPKG that I'll work with. The OW file is already added. This notebook wil thus only work with the file *habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg*_

# General

## Importing functions

In [1]:
from functions.gpkg_funcs import (
    import_gpkg_func,
)

from functions.idx_builder_funcs import (
    tmp_0_idx_df_func,
    HT_idx_df_func,
    group_idx_df_func,

)

from notebooks_dir._03_training_validation_data_split._support._n01_funcs import (
    clean_and_update_inspected_GPKG,
)

## Setting Directory

In [2]:
from paths.OG_paths import(
    #######################################
    #            00_common_dfs            #
    #######################################
    # |    n01_habitat_reference_dfs      |
    # +===================================+ 
    habitat_reference__WD__df_path,
    habitat_reference__s__df_path,
    habitat_reference__WDNF__df_path,

    
    #######################################
    #  03_training_validation_data_split  #
    #######################################
    # | n01_build_selected_pixels_idx_dfs |
    # +===================================+
    # --- manual inspected pixeled gpkg --- #    
    habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path,

    # --- selected pixels IDX dfs --- #
    idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD1_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD2_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD3_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD4_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD5_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD6_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__s1_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__s2_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__s3_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF6_plusOW_p80__selected__gelderland__tmp2__df_path,
)

## Importing packages

In [3]:
import pandas as pd

## Importing files

In [4]:
habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path, 
    layer='habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__layer', 
    index_col='index',
)

In [5]:
# --- Selection reference dfs ---
habitat_reference__WD__df = pd.read_pickle(habitat_reference__WD__df_path)
habitat_reference__s__df = pd.read_pickle(habitat_reference__s__df_path)
habitat_reference__WDNF__df = pd.read_pickle(habitat_reference__WDNF__df_path)

## Update the columns of the gpkg

Update the area col

In [6]:
# habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf = clean_and_update_inspected_GPKG(
#     habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf
# )

In [7]:
# habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf.to_file(
#     filename=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path,
#     layer="habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__layer",
#     driver="GPKG",
# )

## IDX FC plusOW p80 selected df

In [8]:
idx__FC_plusOW_p80__selected__gelderland__tmp2__df, idx__FC_plusOW_p80__selected__gelderland__tmp2__count = tmp_0_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

In [9]:
idx__FC_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path)

# WD-division

## IDX WD1 plusOW p80 selected df

In [10]:
# WD
idx__WD1_plusOW_p80__selected__gelderland__tmp2__df, idx__WD1_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1',
    group_col='WD1_division'
)

In [11]:
idx__WD1_plusOW_p80__selected__gelderland__tmp2__df

_year_str,2017,2018,2019,2020,2021,2022,2023,2024
Remaining,"[GI_11616_1, GI_11616_10, GI_11616_11, GI_1161...","[GI_14424_1, GI_14424_10, GI_14424_100, GI_144...","[GI_10058_1, GI_10058_2, GI_10058_3, GI_10058_...","[GI_10052_4, GI_10052_5, GI_10087_1, GI_10087_...","[GI_11242_1, GI_11242_10, GI_11242_11, GI_1124...","[GI_44881_1, GI_44881_10, GI_44881_11, GI_4488...","[GI_182_1, GI_182_10, GI_182_11, GI_182_12, GI...",[]
Wet Nature,"[GI_41299_1, GI_41299_2, GI_41299_3, GI_41299_...","[GI_18556_1, GI_18556_10, GI_18556_11, GI_1855...",[],"[GI_12951_1, GI_12951_2, GI_12951_3, GI_12951_...",[],"[GI_44936_1, GI_44936_10, GI_44936_11, GI_4493...","[GI_41938_1, GI_41938_10, GI_41938_11, GI_4193...",[]
Open water,[],"[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu..."

In [12]:
idx__WD1_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WD1_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX WD2 plusOW p80 selected df

In [13]:
# WD2
idx__WD2_plusOW_p80__selected__gelderland__tmp2__df, idx__WD2_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1',
    group_col='WD2_division'
)

In [14]:
idx__WD2_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WD2_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX WD3 plusOW p80 selected df

In [15]:
# WD3
idx__WD3_plusOW_p80__selected__gelderland__tmp2__df, idx__WD3_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1',
    group_col='WD3_division'
)

In [16]:
idx__WD3_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WD3_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX WD4 plusOW p80 selected df

In [17]:
# WD4
idx__WD4_plusOW_p80__selected__gelderland__tmp2__df, idx__WD4_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1',
    group_col='WD4_division'
)

In [18]:
idx__WD4_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WD4_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX WD5 plusOW p80 selected df

In [19]:
# WD5
idx__WD5_plusOW_p80__selected__gelderland__tmp2__df, idx__WD5_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1',
    group_col='WD5_division'
)

In [20]:
idx__WD5_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WD5_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX WD6 plusOW p80 selected df

In [21]:
# WD6
idx__WD6_plusOW_p80__selected__gelderland__tmp2__df, idx__WD5_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1',
    group_col='WD6_division'
)

In [22]:
idx__WD6_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WD6_plusOW_p80__selected__gelderland__tmp2__df_path)

# s-division

## IDX s1 plusOW p80 selected df

In [23]:
# s1
idx__s1_plusOW_p80__selected__gelderland__tmp2__df, idx__s1_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__s__df,
    habitat_col='habitatType1',
    group_col='s1_division'
)

In [24]:
idx__s1_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__s1_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX s2 plusOW p80 selected df

In [25]:
# s2
idx__s2_plusOW_p80__selected__gelderland__tmp2__df, idx__s2_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__s__df,
    habitat_col='habitatType1',
    group_col='s2_division'
)

In [26]:
idx__s2_plusOW_p80__selected__gelderland__tmp2__df

_year_str,2017,2018,2019,2020,2021,2022,2023,2024
Remaining,"[GI_11616_1, GI_11616_10, GI_11616_11, GI_1161...","[GI_14426_1, GI_14426_2, GI_14426_3, GI_14426_...","[GI_10067_10, GI_10067_11, GI_10067_12, GI_100...","[GI_10090_1, GI_10090_2, GI_10100_1, GI_10100_...","[GI_11242_1, GI_11242_10, GI_11242_11, GI_1124...",[],"[GI_182_1, GI_182_10, GI_182_11, GI_182_12, GI...",[]
Ven,"[GI_41966_1, GI_41966_10, GI_41966_11, GI_4196...","[GI_18556_1, GI_18556_10, GI_18556_11, GI_1855...",[],"[GI_12951_1, GI_12951_2, GI_12951_3, GI_12951_...",[],"[GI_44936_1, GI_44936_10, GI_44936_11, GI_4493...",[],[]
Vochtige heiden,"[GI_41299_1, GI_41299_2, GI_41299_3, GI_41299_...","[GI_18984_1, GI_18984_10, GI_18984_11, GI_1898...",[],"[GI_18781_1, GI_18781_10, GI_18781_11, GI_1878...",[],[],[],[]
Open water,[],"[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu..."

In [27]:
idx__s2_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__s2_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX s3 plusOW p80 selected df

In [28]:
# s3
idx__s3_plusOW_p80__selected__gelderland__tmp2__df, idx__s3_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__s__df,
    habitat_col='habitatType1',
    group_col='s3_division'
)

In [29]:
idx__s3_plusOW_p80__selected__gelderland__tmp2__df

_year_str,2017,2018,2019,2020,2021,2022,2023,2024
Remaining,"[GI_11616_1, GI_11616_10, GI_11616_11, GI_1161...","[GI_14426_1, GI_14426_2, GI_14426_3, GI_14426_...","[GI_10067_10, GI_10067_11, GI_10067_12, GI_100...","[GI_10090_1, GI_10090_2, GI_10100_1, GI_10100_...","[GI_11242_1, GI_11242_10, GI_11242_11, GI_1124...",[],"[GI_182_1, GI_182_10, GI_182_11, GI_182_12, GI...",[]
Vochtige heiden,"[GI_41299_1, GI_41299_2, GI_41299_3, GI_41299_...","[GI_18984_1, GI_18984_10, GI_18984_11, GI_1898...",[],"[GI_18781_1, GI_18781_10, GI_18781_11, GI_1878...",[],[],[],[]
Ven,[],"[GI_18556_1, GI_18556_10, GI_18556_11, GI_1855...",[],"[GI_12951_1, GI_12951_2, GI_12951_3, GI_12951_...",[],"[GI_44936_1, GI_44936_10, GI_44936_11, GI_4493...",[],[]
Open water,[],"[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu..."

In [30]:
idx__s3_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__s3_plusOW_p80__selected__gelderland__tmp2__df_path)

# WDNF

## IDX WDNF1 plusOW p80 selected df

In [31]:
# WDNF
idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df, idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WDNF__df,
    habitat_col='habitatType1',
    group_col='WDNF1_division'
)

In [32]:
idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df

_year_str,2017,2018,2019,2020,2021,2022,2023,2024
Remaining,"[GI_11616_1, GI_11616_10, GI_11616_11, GI_1161...","[GI_14424_1, GI_14424_10, GI_14424_100, GI_144...","[GI_10058_1, GI_10058_2, GI_10058_3, GI_10058_...","[GI_10052_4, GI_10052_5, GI_10087_1, GI_10087_...","[GI_11242_1, GI_11242_10, GI_11242_11, GI_1124...","[GI_44881_1, GI_44881_10, GI_44881_11, GI_4488...","[GI_182_1, GI_182_10, GI_182_11, GI_182_12, GI...",[]
Wet Nature,"[GI_41299_1, GI_41299_2, GI_41299_3, GI_41299_...","[GI_18556_1, GI_18556_10, GI_18556_11, GI_1855...",[],"[GI_12951_1, GI_12951_2, GI_12951_3, GI_12951_...",[],"[GI_44936_1, GI_44936_10, GI_44936_11, GI_4493...","[GI_41938_1, GI_41938_10, GI_41938_11, GI_4193...",[]
Open water,[],"[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu..."

In [33]:
idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX WDNF2 plusOW p80 selected df

In [34]:
# WDNF2
idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__df, idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WDNF__df,
    habitat_col='habitatType1',
    group_col='WDNF2_division'
)

In [35]:
idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX WDNF3 plusOW p80 selected df

In [36]:
# WD3
idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__df, idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WDNF__df,
    habitat_col='habitatType1',
    group_col='WDNF3_division'
)

In [37]:
idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX WDNF4 plusOW p80 selected df

In [38]:
# WDNF4
idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__df, idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WDNF__df,
    habitat_col='habitatType1',
    group_col='WDNF4_division'
)

In [39]:
idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX WDNF5 plusOW p80 selected df

In [40]:
# WDNF5
idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__df, idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WDNF__df,
    habitat_col='habitatType1',
    group_col='WDNF5_division'
)

In [41]:
idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__df_path)

## IDX WDNF6 plusOW p80 selected df

In [42]:
# WDNF6
idx__WDNF6_plusOW_p80__selected__gelderland__tmp2__df, idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__count = group_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WDNF__df,
    habitat_col='habitatType1',
    group_col='WDNF6_division'
)

In [43]:
idx__WDNF6_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__WDNF6_plusOW_p80__selected__gelderland__tmp2__df_path)

End of the Notebook