_This notebook splits the habitat data into a training and a validation dataset for each division strategy separately._

## Importing functions

In [1]:
from functions.gpkg_funcs import (
    import_gpkg_func,
)

from functions.idx_pixel_count_funcs import (
    unique_idx_area_func,
)

from notebooks_dir._03_training_validation_data_split._support._n03_funcs import (
    train_val_split_automation,
)

## Setting Directory

In [2]:
from paths.OG_paths import(
    #######################################
    #  03_training_validation_data_split  #
    #######################################
    # | n01_build_selected_pixels_idx_dfs |
    # +===================================+
    # --- manual inspected pixeled gpkg --- #    
    habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path,
    
    # --- selected pixels IDX dfs --- #
    idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD1_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD2_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD3_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD4_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD5_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD6_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__s1_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__s2_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__s3_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WDNF6_plusOW_p80__selected__gelderland__tmp2__df_path,


    # +=====================================+
    # | n03_training_validation_split_carto |
    # +=====================================+
    # --- idx training validation dfs --- #
    # DIR
    training_validation__dir,
)

## Importing packages

In [3]:
import pandas as pd

## Importing files

In [4]:
habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path, 
    layer='habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__layer', 
    index_col='index',
)

In [5]:
idx__FC_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD1_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD1_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD2_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD2_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD3_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD3_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD4_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD4_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD5_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD5_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD6_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD6_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__s1_plusOW_p80_selected_gelderland_tmp2_df = pd.read_pickle(idx__s1_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__s2_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__s2_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__s3_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__s3_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__FC_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WDNF6_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WDNF6_plusOW_p80__selected__gelderland__tmp2__df_path)

## Calculating the unique area of each pixel

_This step calculates the total area of the unique ID's. If a ID is present in multiple columns, then it is only taken into account once. Based on this a list is build that determines the amount of area that should be included in the training/validation set_

### WD1 - area_selection

In [6]:
WD1_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD1_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WD1 areas per row:\n" + WD1_area_text)

WD1 areas per row:
Remaining: 311622.00 pixels
Wet Nature: 2207.00 pixels
Open water: 1279.00 pixels

In [7]:
WD1_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 1200,
    "Open water": 450,
}

### WD2 - area_selection

In [8]:
WD2_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD2_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WD2 areas per row:\n" + WD2_area_text)

WD2 areas per row:
Remaining: 129211.00 pixels
Wet Nature: 2207.00 pixels
Open water: 1279.00 pixels

In [9]:
WD2_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 1200,
    "Open water": 450,
}

### WD3 - area_selection

In [10]:
WD3_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WD3 areas per row:\n" + WD3_area_text)

WD3 areas per row:
Remaining: 311622.00 pixels
Semi-Wet Nature: 2063.00 pixels
Wet Nature: 144.00 pixels
Open water: 1279.00 pixels

In [11]:
WD3_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 150,
    "Semi-Wet Nature": 750,
    "Open water": 450,
}

### WD4 - area_selection

In [12]:
WD4_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD4_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WD4 areas per row:\n" + WD4_area_text)

WD4 areas per row:
Remaining: 129211.00 pixels
Semi-Wet Nature: 2063.00 pixels
Wet Nature: 144.00 pixels
Open water: 1279.00 pixels

In [13]:
WD4_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 150,
    "Semi-Wet Nature": 750,
    "Open water": 450,
}

### WD5 - area_selection

In [14]:
WD5_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD5_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WD5 areas per row:\n" + WD5_area_text)

WD5 areas per row:
Remaining: 311622.00 pixels
Semi-Wet Nature: 2063.00 pixels
Open water: 1423.00 pixels

In [15]:
WD5_at1_dict = {
    "Remaining": 3000,
    "Semi-Wet Nature": 1200,
    "Open water": 600,
}

### WD6 - area_selection

In [16]:
WD6_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD6_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WD5 areas per row:\n" + WD6_area_text)

WD5 areas per row:
Remaining: 129211.00 pixels
Semi-Wet Nature: 2063.00 pixels
Open water: 1423.00 pixels

In [17]:
WD6_at1_dict = {
    "Remaining": 3000,
    "Semi-Wet Nature": 1200,
    "Open water": 600,
}

### S1 - area_selection

In [18]:
s1_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__s1_plusOW_p80_selected_gelderland_tmp2_df,
    area_col="Shape_Area",
    as_text=True,
)

print("S1 areas per row:\n" + s1_area_text)

S1 areas per row:
Remaining: 122724.00 pixels
Overgangs- & trilven: 106.00 pixels
Vochtige heiden: 1286.00 pixels
Zwakgebufferde vennen: 79.00 pixels
Zure vennen: 65.00 pixels
Open water: 1279.00 pixels

In [19]:
s1_at1_dict = {
    "Remaining": 1500,
    "Overgangs- & trilven": 80,
    "Vochtige heiden": 800,
    "Zwakgebufferde vennen": 60,
    "Zure vennen": 45,
    "Open water": 450,
}

### S2 - area_selection

In [20]:
s2_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__s2_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("S2 areas per row:\n" + s2_area_text)

S2 areas per row:
Remaining: 129357.00 pixels
Ven: 250.00 pixels
Vochtige heiden: 1286.00 pixels
Open water: 1279.00 pixels

In [21]:
s2_at1_dict = {
    'Remaining': 1500,
    "Ven": 175,
    "Vochtige heiden": 800,
    "Open water": 450,
}

### S3 - area_selection

In [22]:
s3_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__s3_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("S3 areas per row:\n" + s3_area_text)

S3 areas per row:
Remaining: 129463.00 pixels
Vochtige heiden: 1286.00 pixels
Ven: 144.00 pixels
Open water: 1279.00 pixels

In [23]:
s3_at1_dict = {
    'Remaining': 1500,
    "Ven": 150,
    "Vochtige heiden": 800,
    "Open water": 450,
}

### WDNF1 - area_selection

In [24]:
WDNF1_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WD1 areas per row:\n" + WDNF1_area_text)

WD1 areas per row:
Remaining: 311622.00 pixels
Wet Nature: 1930.00 pixels
Open water: 1279.00 pixels

In [25]:
WDNF1_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 1200,
    "Open water": 450,
}

### WDNF2 - area_selection

In [26]:
WDNF2_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WDNF2 areas per row:\n" + WD2_area_text)

WDNF2 areas per row:
Remaining: 129211.00 pixels
Wet Nature: 2207.00 pixels
Open water: 1279.00 pixels

In [27]:
WDNF2_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 1200,
    "Open water": 450,
}

### WDNF3 - area_selection

In [28]:
WDNF3_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WDNF3 areas per row:\n" + WD3_area_text)

WDNF3 areas per row:
Remaining: 311622.00 pixels
Semi-Wet Nature: 2063.00 pixels
Wet Nature: 144.00 pixels
Open water: 1279.00 pixels

In [29]:
WDNF3_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 150,
    "Semi-Wet Nature": 750,
    "Open water": 450,
}

### WDNF4 - area_selection

In [30]:
WDNF4_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WDNF4 areas per row:\n" + WD4_area_text)

WDNF4 areas per row:
Remaining: 129211.00 pixels
Semi-Wet Nature: 2063.00 pixels
Wet Nature: 144.00 pixels
Open water: 1279.00 pixels

In [31]:
WDNF4_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 150,
    "Semi-Wet Nature": 750,
    "Open water": 450,
}

### WDNF5 - area_selection

In [32]:
WDNF5_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WDNF5 areas per row:\n" + WD5_area_text)

WDNF5 areas per row:
Remaining: 311622.00 pixels
Semi-Wet Nature: 2063.00 pixels
Open water: 1423.00 pixels

In [33]:
WDNF5_at1_dict = {
    "Remaining": 3000,
    "Semi-Wet Nature": 1200,
    "Open water": 600,
}

### WDNF6 - area_selection

In [34]:
WDNF6_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF6_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WDNF5 areas per row:\n" + WD6_area_text)

WDNF5 areas per row:
Remaining: 129211.00 pixels
Semi-Wet Nature: 2063.00 pixels
Open water: 1423.00 pixels

In [35]:
WDNF6_at1_dict = {
    "Remaining": 3000,
    "Semi-Wet Nature": 1200,
    "Open water": 600,
}

## Splitting the data and saving as gpkgs

### WD1 split

#### WD1 at1

In [36]:
# at1
WD1_at1_sum_df, WD1_at1_train_pixel_area_df_exp, WD1_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD1_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD1_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=40,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Remaining'],
);

display(WD1_at1_sum_df)
display(WD1_at1_train_pixel_area_df_exp)
display(WD1_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD1_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD1_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD1_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2264.0,750.0,751.0,0.0,0.0,2264,751,0,297574,0,0,125,60,0
Wet Nature,900.0,922.0,300.0,309.0,0.0,0.0,922,309,0,240,0,0,89,12,0
Open water,337.5,322.0,112.5,130.0,0.0,0.0,322,130,0,0,0,0,16,7,0

### WD2 split

#### WD2 at1

In [37]:
# at1
WD2_at1_sum_df, WD2_at1_train_pixel_area_df_exp, WD2_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD2_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD2_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD2_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=42,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Remaining'],
);

display(WD2_at1_sum_df)
display(WD2_at1_train_pixel_area_df_exp)
display(WD2_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD2_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD2_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD2_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2251.0,750.0,768.0,0.0,0.0,2251,768,0,116281,0,0,122,58,0
Wet Nature,900.0,902.0,300.0,304.0,0.0,0.0,902,304,0,333,0,0,87,11,0
Open water,337.5,339.0,112.5,113.0,0.0,0.0,339,113,0,0,0,0,16,7,0

### WD3 split

#### WD3 at1

In [38]:
# at1
WD3_at1_sum_df, WD3_at1_train_pixel_area_df_exp, WD3_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD3_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD3_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=3,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Semi-Wet Nature', 'Remaining'],
);

display(WD3_at1_sum_df)
display(WD3_at1_train_pixel_area_df_exp)
display(WD3_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD3_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD3_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD3_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD3_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2100.0,2122.0,900.0,918.0,0.0,0.0,2122,918,0,302147,0,0,126,57,0
Semi-Wet Nature,525.0,531.0,225.0,232.0,0.0,0.0,531,232,0,726,0,0,44,8,0
Wet Nature,105.0,98.0,45.0,42.0,0.0,0.0,98,42,0,0,0,0,16,1,0
Open water,315.0,306.0,135.0,146.0,0.0,0.0,306,146,0,0,0,0,16,7,0

### WD4 split

#### WD4 at1

In [39]:
# at1
WD4_at1_sum_df, WD4_at1_train_pixel_area_df_exp, WD4_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD4_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD4_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD4_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=1,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Semi-Wet Nature', 'Remaining'],
);

display(WD4_at1_sum_df)
display(WD4_at1_train_pixel_area_df_exp)
display(WD4_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD4_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD4_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD4_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD4_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2100.0,2117.0,900.0,913.0,0.0,0.0,2117,913,0,119926,0,0,136,56,0
Semi-Wet Nature,525.0,530.0,225.0,231.0,0.0,0.0,530,231,0,1066,0,0,49,7,0
Wet Nature,105.0,98.0,45.0,42.0,0.0,0.0,98,42,0,0,0,0,16,1,0
Open water,315.0,318.0,135.0,134.0,0.0,0.0,318,134,0,0,0,0,16,7,0

### WD5 split

#### WD5 at1

In [40]:
# at1
WD5_at1_sum_df, WD5_at1_train_pixel_area_df_exp, WD5_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD5_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD5_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD5_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=2,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Semi-Wet Nature', 'Remaining'],
);

display(WD5_at1_sum_df)
display(WD5_at1_train_pixel_area_df_exp)
display(WD5_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD5_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD5_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD5_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD5_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2279.0,750.0,763.0,0.0,0.0,2279,763,0,299511,0,0,123,63,0
Semi-Wet Nature,900.0,902.0,300.0,318.0,0.0,0.0,902,318,0,76,0,0,76,14,0
Open water,450.0,447.0,150.0,145.0,0.0,0.0,447,145,0,0,0,0,32,8,0

### WD6 split

#### WD6 at1

In [41]:
# at1
WD6_at1_sum_df, WD6_at1_train_pixel_area_df_exp, WD6_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD6_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD6_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD6_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=3,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Semi-Wet Nature', 'Remaining'],
);

display(WD6_at1_sum_df)
display(WD6_at1_train_pixel_area_df_exp)
display(WD6_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD6_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD6_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD6_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD6_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD6_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD6_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2261.0,750.0,756.0,0.0,0.0,2261,756,0,119737,0,0,132,58,0
Semi-Wet Nature,900.0,930.0,300.0,312.0,0.0,0.0,930,312,0,37,0,0,81,14,0
Open water,450.0,450.0,150.0,142.0,0.0,0.0,450,142,0,0,0,0,32,8,0

### S1 - split

#### s1 at1

In [42]:
# at1
s1_at1_sum_df, s1_at1_train_pixel_area_df_exp, s1_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="s1_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__s1_plusOW_p80_selected_gelderland_tmp2_df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=s1_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=42,
    seed=44,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=[
        'Open water', 'Zure vennen', 'Zwakgebufferde vennen',
        'Overgangs- & trilven', 'Vochtige heiden', 'Remaining'
    ]
);

display(s1_at1_sum_df)
display(s1_at1_train_pixel_area_df_exp)
display(s1_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__s1_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__s1_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__s1_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__s1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__s1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__s1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,1050.0,1058.0,450.0,453.0,0.0,0.0,1058,453,0,116842,0,0,59,29,0
Overgangs- & trilven,56.0,43.0,24.0,13.0,0.0,0.0,43,13,0,0,0,0,3,1,0
Vochtige heiden,560.0,514.0,240.0,196.0,0.0,0.0,514,196,0,0,0,0,47,7,0
Zwakgebufferde vennen,42.0,36.0,18.0,43.0,0.0,0.0,36,43,0,0,0,0,7,0,0
Zure vennen,31.5,41.0,13.5,21.0,0.0,0.0,41,21,0,3,0,0,8,0,0
Open water,315.0,346.0,135.0,145.0,0.0,0.0,346,145,0,0,0,0,16,6,0

### S2 - split

#### s2 at1

In [43]:
# at1
s2_at1_sum_df, s2_at1_train_pixel_area_df_exp, s2_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="s2_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__s2_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=s2_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=59,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Ven', 'Vochtige heiden', 'Remaining']
);

display(s2_at1_sum_df)
display(s2_at1_train_pixel_area_df_exp)
display(s2_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__s2_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__s2_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__s2_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__s2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__s2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__s2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,1125.00,1130.0,375.00,390.0,0.0,0.0,1130,390,0,124467,0,0,63,29,0
Ven,131.25,135.0,43.75,46.0,0.0,0.0,135,46,0,9,0,0,17,2,0
Vochtige heiden,600.00,506.0,200.00,109.0,0.0,0.0,506,109,0,0,0,0,47,7,0
Open water,337.50,325.0,112.50,127.0,0.0,0.0,325,127,0,0,0,0,16,7,0

### S3 - split

#### s3 at1

In [ ]:
clkjvzsldkjf

[train_val_split_automation] overwrite=False and no split files + no associated GPKGs -> computed split and saved:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__s3_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__s3_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__s3_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] Created/overwritten: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__s3_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] Created/overwritten: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__s3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] Created/overwritten (RD): D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\Carto [RD]\validation_pixels__s3_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] Created/overwritten (UTM): D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__s3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,1125.0,1136.0,375.0,395.0,0.0,0.0,1136,395,0,122585,0,0,67,31,0
Vochtige heiden,600.0,524.0,200.0,136.0,0.0,0.0,524,136,0,0,0,0,47,7,0
Ven,112.5,103.0,37.5,37.0,0.0,0.0,103,37,0,0,0,0,16,1,0
Open water,337.5,328.0,112.5,124.0,0.0,0.0,328,124,0,0,0,0,16,7,0

### WDNF1 - area_selection

In [45]:
WDNF1_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WD1 areas per row:\n" + WDNF1_area_text)

WD1 areas per row:
Remaining: 311622.00 pixels
Wet Nature: 1930.00 pixels
Open water: 1279.00 pixels

In [46]:
WDNF1_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 1200,
    "Open water": 450,
}

### WDNF2 - area_selection

In [47]:
WDNF2_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WDNF2 areas per row:\n" + WD2_area_text)

WDNF2 areas per row:
Remaining: 129211.00 pixels
Wet Nature: 2207.00 pixels
Open water: 1279.00 pixels

In [48]:
WDNF2_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 1200,
    "Open water": 450,
}

### WDNF3 - area_selection

In [49]:
WDNF3_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WDNF3 areas per row:\n" + WD3_area_text)

WDNF3 areas per row:
Remaining: 311622.00 pixels
Semi-Wet Nature: 2063.00 pixels
Wet Nature: 144.00 pixels
Open water: 1279.00 pixels

In [50]:
WDNF3_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 150,
    "Semi-Wet Nature": 750,
    "Open water": 450,
}

### WDNF4 - area_selection

In [51]:
WDNF4_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WDNF4 areas per row:\n" + WD4_area_text)

WDNF4 areas per row:
Remaining: 129211.00 pixels
Semi-Wet Nature: 2063.00 pixels
Wet Nature: 144.00 pixels
Open water: 1279.00 pixels

In [52]:
WDNF4_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 150,
    "Semi-Wet Nature": 750,
    "Open water": 450,
}

### WDNF5 - area_selection

In [53]:
WDNF5_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WDNF5 areas per row:\n" + WD5_area_text)

WDNF5 areas per row:
Remaining: 311622.00 pixels
Semi-Wet Nature: 2063.00 pixels
Open water: 1423.00 pixels

In [54]:
WDNF5_at1_dict = {
    "Remaining": 3000,
    "Semi-Wet Nature": 1200,
    "Open water": 600,
}

### WDNF6 - area_selection

In [55]:
WDNF6_area_text = unique_idx_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF6_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="Shape_Area",
    as_text=True,
)

print("WDNF5 areas per row:\n" + WD6_area_text)

WDNF5 areas per row:
Remaining: 129211.00 pixels
Semi-Wet Nature: 2063.00 pixels
Open water: 1423.00 pixels

In [56]:
WDNF6_at1_dict = {
    "Remaining": 3000,
    "Semi-Wet Nature": 1200,
    "Open water": 600,
}

## Splitting the data and saving as gpkgs

### WD1 split

#### WD1 at1

In [57]:
# at1
WD1_at1_sum_df, WD1_at1_train_pixel_area_df_exp, WD1_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD1_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD1_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=40,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Remaining'],
);

display(WD1_at1_sum_df)
display(WD1_at1_train_pixel_area_df_exp)
display(WD1_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD1_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD1_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD1_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2264.0,750.0,751.0,0.0,0.0,2264,751,0,297574,0,0,125,60,0
Wet Nature,900.0,922.0,300.0,309.0,0.0,0.0,922,309,0,240,0,0,89,12,0
Open water,337.5,322.0,112.5,130.0,0.0,0.0,322,130,0,0,0,0,16,7,0

### WD2 split

#### WD2 at1

In [58]:
# at1
WD2_at1_sum_df, WD2_at1_train_pixel_area_df_exp, WD2_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD2_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD2_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD2_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=42,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Remaining'],
);

display(WD2_at1_sum_df)
display(WD2_at1_train_pixel_area_df_exp)
display(WD2_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD2_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD2_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD2_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2251.0,750.0,768.0,0.0,0.0,2251,768,0,116281,0,0,122,58,0
Wet Nature,900.0,902.0,300.0,304.0,0.0,0.0,902,304,0,333,0,0,87,11,0
Open water,337.5,339.0,112.5,113.0,0.0,0.0,339,113,0,0,0,0,16,7,0

### WD3 split

#### WD3 at1

In [59]:
# at1
WD3_at1_sum_df, WD3_at1_train_pixel_area_df_exp, WD3_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD3_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD3_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=3,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Semi-Wet Nature', 'Remaining'],
);

display(WD3_at1_sum_df)
display(WD3_at1_train_pixel_area_df_exp)
display(WD3_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD3_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD3_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD3_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD3_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2100.0,2122.0,900.0,918.0,0.0,0.0,2122,918,0,302147,0,0,126,57,0
Semi-Wet Nature,525.0,531.0,225.0,232.0,0.0,0.0,531,232,0,726,0,0,44,8,0
Wet Nature,105.0,98.0,45.0,42.0,0.0,0.0,98,42,0,0,0,0,16,1,0
Open water,315.0,306.0,135.0,146.0,0.0,0.0,306,146,0,0,0,0,16,7,0

### WD4 split

#### WD4 at1

In [60]:
# at1
WD4_at1_sum_df, WD4_at1_train_pixel_area_df_exp, WD4_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD4_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD4_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD4_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=1,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Semi-Wet Nature', 'Remaining'],
);

display(WD4_at1_sum_df)
display(WD4_at1_train_pixel_area_df_exp)
display(WD4_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD4_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD4_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD4_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD4_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2100.0,2117.0,900.0,913.0,0.0,0.0,2117,913,0,119926,0,0,136,56,0
Semi-Wet Nature,525.0,530.0,225.0,231.0,0.0,0.0,530,231,0,1066,0,0,49,7,0
Wet Nature,105.0,98.0,45.0,42.0,0.0,0.0,98,42,0,0,0,0,16,1,0
Open water,315.0,318.0,135.0,134.0,0.0,0.0,318,134,0,0,0,0,16,7,0

### WD5 split

#### WD5 at1

In [61]:
# at1
WD5_at1_sum_df, WD5_at1_train_pixel_area_df_exp, WD5_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD5_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD5_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD5_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=2,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Semi-Wet Nature', 'Remaining'],
);

display(WD5_at1_sum_df)
display(WD5_at1_train_pixel_area_df_exp)
display(WD5_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD5_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD5_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD5_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD5_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2279.0,750.0,763.0,0.0,0.0,2279,763,0,299511,0,0,123,63,0
Semi-Wet Nature,900.0,902.0,300.0,318.0,0.0,0.0,902,318,0,76,0,0,76,14,0
Open water,450.0,447.0,150.0,145.0,0.0,0.0,447,145,0,0,0,0,32,8,0

### WD6 split

#### WD6 at1

In [62]:
# at1
WD6_at1_sum_df, WD6_at1_train_pixel_area_df_exp, WD6_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WD6_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD6_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD6_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=3,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Semi-Wet Nature', 'Remaining'],
);

display(WD6_at1_sum_df)
display(WD6_at1_train_pixel_area_df_exp)
display(WD6_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD6_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WD6_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WD6_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WD6_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WD6_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WD6_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2261.0,750.0,756.0,0.0,0.0,2261,756,0,119737,0,0,132,58,0
Semi-Wet Nature,900.0,930.0,300.0,312.0,0.0,0.0,930,312,0,37,0,0,81,14,0
Open water,450.0,450.0,150.0,142.0,0.0,0.0,450,142,0,0,0,0,32,8,0

### S1 - split

#### s1 at1

In [63]:
# at1
s1_at1_sum_df, s1_at1_train_pixel_area_df_exp, s1_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="s1_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__s1_plusOW_p80_selected_gelderland_tmp2_df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=s1_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=42,
    seed=44,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=[
        'Open water', 'Zure vennen', 'Zwakgebufferde vennen',
        'Overgangs- & trilven', 'Vochtige heiden', 'Remaining'
    ]
);

display(s1_at1_sum_df)
display(s1_at1_train_pixel_area_df_exp)
display(s1_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__s1_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__s1_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__s1_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__s1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__s1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__s1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,1050.0,1058.0,450.0,453.0,0.0,0.0,1058,453,0,116842,0,0,59,29,0
Overgangs- & trilven,56.0,43.0,24.0,13.0,0.0,0.0,43,13,0,0,0,0,3,1,0
Vochtige heiden,560.0,514.0,240.0,196.0,0.0,0.0,514,196,0,0,0,0,47,7,0
Zwakgebufferde vennen,42.0,36.0,18.0,43.0,0.0,0.0,36,43,0,0,0,0,7,0,0
Zure vennen,31.5,41.0,13.5,21.0,0.0,0.0,41,21,0,3,0,0,8,0,0
Open water,315.0,346.0,135.0,145.0,0.0,0.0,346,145,0,0,0,0,16,6,0

### S2 - split

#### s2 at1

In [64]:
# at1
s2_at1_sum_df, s2_at1_train_pixel_area_df_exp, s2_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="s2_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__s2_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=s2_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=59,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Ven', 'Vochtige heiden', 'Remaining']
);

display(s2_at1_sum_df)
display(s2_at1_train_pixel_area_df_exp)
display(s2_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__s2_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__s2_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__s2_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__s2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__s2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__s2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,1125.00,1130.0,375.00,390.0,0.0,0.0,1130,390,0,124467,0,0,63,29,0
Ven,131.25,135.0,43.75,46.0,0.0,0.0,135,46,0,9,0,0,17,2,0
Vochtige heiden,600.00,506.0,200.00,109.0,0.0,0.0,506,109,0,0,0,0,47,7,0
Open water,337.50,325.0,112.50,127.0,0.0,0.0,325,127,0,0,0,0,16,7,0

### WDNF1 split

#### WDNF1 at1

In [65]:
# at1
WDNF1_at1_sum_df, WDNF1_at1_train_pixel_area_df_exp, WDNF1_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WDNF1_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF1_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WDNF1_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=45,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Remaining'],
);

display(WDNF1_at1_sum_df)
display(WDNF1_at1_train_pixel_area_df_exp)
display(WDNF1_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF1_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF1_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WDNF1_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WDNF1_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WDNF1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WDNF1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2263.0,750.0,784.0,0.0,0.0,2263,784,0,298182,0,0,130,55,0
Wet Nature,900.0,884.0,300.0,286.0,0.0,0.0,884,286,0,0,0,0,86,14,0
Open water,337.5,344.0,112.5,108.0,0.0,0.0,344,108,0,0,0,0,16,7,0

### WDNF2 split

#### WDNF2 at1

In [66]:
# at1
WDNF2_at1_sum_df, WDNF2_at1_train_pixel_area_df_exp, WDNF2_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WDNF2_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF2_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WD2_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=45,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Remaining'],
);

display(WDNF2_at1_sum_df)
display(WDNF2_at1_train_pixel_area_df_exp)
display(WDNF2_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF2_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF2_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WDNF2_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WDNF2_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WDNF2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WDNF2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2277.0,750.0,782.0,0.0,0.0,2277,782,0,118619,0,0,130,53,0
Wet Nature,900.0,865.0,300.0,281.0,0.0,0.0,865,281,0,0,0,0,86,14,0
Open water,337.5,344.0,112.5,108.0,0.0,0.0,344,108,0,0,0,0,16,7,0

### WDNF3 split

#### WDNF3 at1

In [67]:
# at1
WDNF3_at1_sum_df, WDNF3_at1_train_pixel_area_df_exp, WDNF3_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WDNF3_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF3_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WDNF3_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=3,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Semi-Wet Nature', 'Remaining'],
);

display(WDNF3_at1_sum_df)
display(WDNF3_at1_train_pixel_area_df_exp)
display(WDNF3_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF3_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF3_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WDNF3_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WDNF3_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WDNF3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WDNF3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2100.0,2113.0,900.0,922.0,0.0,0.0,2113,922,0,301008,0,0,141,58,0
Semi-Wet Nature,525.0,549.0,225.0,255.0,0.0,0.0,549,255,0,733,0,0,56,8,0
Wet Nature,105.0,100.0,45.0,40.0,0.0,0.0,100,40,0,0,0,0,16,1,0
Open water,315.0,328.0,135.0,124.0,0.0,0.0,328,124,0,0,0,0,16,7,0

### WDNF4 split

#### WDNF4 at1

In [68]:
# at1
WDNF4_at1_sum_df, WDNF4_at1_train_pixel_area_df_exp, WDNF4_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WDNF4_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF4_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WDNF4_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=3,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Wet Nature', 'Semi-Wet Nature', 'Remaining'],
);

display(WDNF4_at1_sum_df)
display(WDNF4_at1_train_pixel_area_df_exp)
display(WDNF4_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF4_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF4_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WDNF4_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WDNF4_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WDNF4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WDNF4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2100.0,2107.0,900.0,931.0,0.0,0.0,2107,931,0,117343,0,0,127,63,0
Semi-Wet Nature,525.0,525.0,225.0,230.0,0.0,0.0,525,230,0,342,0,0,48,11,0
Wet Nature,105.0,99.0,45.0,41.0,0.0,0.0,99,41,0,0,0,0,16,1,0
Open water,315.0,307.0,135.0,145.0,0.0,0.0,307,145,0,0,0,0,16,7,0

### WDNF5 split

#### WDNF5 at1

In [69]:
# at1
WDNF5_at1_sum_df, WDNF5_at1_train_pixel_area_df_exp, WDNF5_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WDNF5_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF5_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WDNF5_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=5,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Semi-Wet Nature', 'Remaining'],
);

display(WDNF5_at1_sum_df)
display(WDNF5_at1_train_pixel_area_df_exp)
display(WDNF5_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF5_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF5_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WDNF5_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WDNF5_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WDNF5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WDNF5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2255.0,750.0,753.0,0.0,0.0,2255,753,0,299387,0,0,138,57,0
Semi-Wet Nature,900.0,821.0,300.0,217.0,0.0,0.0,821,217,0,0,0,0,70,13,0
Open water,450.0,447.0,150.0,145.0,0.0,0.0,447,145,0,0,0,0,32,8,0

### WDNF6 split

#### WDNF6 at1

In [70]:
# at1
WDNF6_at1_sum_df, WDNF6_at1_train_pixel_area_df_exp, WDNF6_at1_validation_pixel_area_df_exp = train_val_split_automation(
    run_id="WDNF6_plusOW_p80_tmp2_cart_at1__gelderland__RD",
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WDNF6_plusOW_p80__selected__gelderland__tmp2__df,
    output_dir=training_validation__dir,
    cap_pixels_by_class=WDNF6_at1_dict,
    train_pct=0.75,
    val_pct=0.25,
    test_pct=0.0,
    area_col="Shape_Area",
    large_polygon_threshold=36,
    seed=5,
    overwrite=False,
    ml_epsg="EPSG:32631",
    pixels_row_order=['Open water', 'Semi-Wet Nature', 'Remaining'],
);

display(WDNF6_at1_sum_df)
display(WDNF6_at1_train_pixel_area_df_exp)
display(WDNF6_at1_validation_pixel_area_df_exp)

[train_val_split_automation] overwrite=False and all split files exist -> loaded:
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF6_plusOW_p80_tmp2_training_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_idx_dfs\idx__WDNF6_plusOW_p80_tmp2_validation_at1__gelderland__df.pkl
  - D:\Thesis\10.Thesis_Data\03_training_validation_data\02_training_validation_split_sum_df\sum__WDNF6_plusOW_p80_tmp2_at1__gelderland__df.pkl
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\Carto [RD]\training_polys__WDNF6_plusOW_p80_tmp2_cart_at1__gelderland__RD__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_training_data_gpkgs\ML_approach [UTM32631]\training_pixels__WDNF6_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg
[train_val_split_automation] overwrite=False and exists -> kept: D:\Thesis\10.Thesis_Data\03_training_validation_data\03_validation_data_gpkgs\ML_approach [UTM32631]\validation_pixels__WDNF6_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg.gpkg

,target_train_pxls,got_train_pxls,target_val_pxls,got_val_pxls,target_test_pxls,got_test_pxls,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,2250.0,2277.0,750.0,764.0,0.0,0.0,2277,764,0,117943,0,0,140,58,0
Semi-Wet Nature,900.0,830.0,300.0,208.0,0.0,0.0,830,208,0,0,0,0,70,13,0
Open water,450.0,439.0,150.0,136.0,0.0,0.0,439,136,0,0,0,0,32,8,0

End of the Notebook