_This Notebook imports and assesses (accuracy and f1-score) the SpheerApp classifications._

## Importing functions

In [1]:
from notebooks_dir._05_output_validation._support._n01_full_workflow import (
    building_carto_clas_acc_dfs,
)

## Setting Directory

In [2]:
from paths.OG_paths import (
    #######################################
    #  03_training_validation_data_split  #
    #######################################
    # |   n03_training_validation_split   |
    # +===================================+
    # --- training validation GPKGs UTM32631 --- #
    validation_cart__RD__gpkgs_dir,


    #######################################
    #         05_output_validation        #
    #######################################
    # |     n01_checking_carto_results    |
    # +===================================+
    carto_output_main__dir,
)

#### Symbol definitions

- $N$: total number of samples.
- $C$: number of classes.
- $y_i$: true (ground-truth) label of sample $i$.
- $\hat{y}_i$: predicted label of sample $i$.
- $\mathbf{1}(\hat{y}_i=y_i)$: indicator function; equals 1 if the prediction is correct, else 0.

Per class $c$ (one-vs-rest view):
- $TP_c$ (true positives): number of samples with true class $c$ predicted as $c$.
- $FP_c$ (false positives): number of samples with true class $\neq c$ predicted as $c$.
- $FN_c$ (false negatives): number of samples with true class $c$ predicted as $\neq c$.
- $P_c$: precision for class $c$.
- $R_c$: recall for class $c$.
- $F1_c$: F1-score for class $c$.

Weights for weighted F1:
- $n_c$: support of class $c$ (number of samples whose true label is $c$).
- $\frac{n_c}{N}$: class weight used in the weighted average.

### F1 explanation

_The F1-score is the harmonic mean of Precision and recall. It's high only when both precision (few false positives) and Recall (few false negatives) are high._

$$
F1 = \frac{2PR}{P+R}
$$

where

$$
P=\frac{TP}{TP+FP}, \qquad R=\frac{TP}{TP+FN}
$$

Equivalent form:

$$
F1=\frac{2TP}{2TP+FP+FN}
$$

### Accuracy
$$
\text{Accuracy}=\frac{\sum_{i=1}^{N}\mathbf{1}(\hat{y}_i=y_i)}{N}
$$

Equivalently (multiclass):
$$
\text{Accuracy}=\frac{\sum_{c=1}^{C} TP_c}{N}
$$

### Precision / Recall (per class c)
$$
P_c=\frac{TP_c}{TP_c+FP_c}
\qquad
R_c=\frac{TP_c}{TP_c+FN_c}
$$

### F1 (per class c)
$$
F1_c=\frac{2P_cR_c}{P_c+R_c}
=\frac{2TP_c}{2TP_c+FP_c+FN_c}
$$

### Macro F1
$$
F1_{\text{macro}}=\frac{1}{C}\sum_{c=1}^{C} F1_c
$$

### Weighted F1
Let $n_c$ be the support (number of true samples) for class $c$, and $N=\sum_{c=1}^{C} n_c$.
$$
F1_{\text{weighted}}=\sum_{c=1}^{C}\left(\frac{n_c}{N}\right)F1_c
$$

## Carto WD scores

### Carto WD1

In [3]:
# result_stats WD1 at1
WD1_at1__result_stats_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WD1_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WD1_at1__result_stats_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WD1_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,acc_remaining,f1_remaining,prec_remaining,rec_remaining,n_remaining,acc_wet_nature,f1_wet_nature,prec_wet_nature,rec_wet_nature,n_wet_nature
0,2017,244,0.92,0.90,0.92,NaN,NaN,NaN,NaN,0,0.97,0.86,0.77,0.97,61,0.90,0.94,0.99,0.90,183
1,2018,337,0.86,0.57,0.88,NaN,NaN,NaN,NaN,0,0.94,0.94,0.94,0.94,229,0.69,0.77,0.85,0.69,108
2,2019,185,0.99,0.67,1.00,1.0,1.0,1.0,1.0,36,0.99,1.00,1.00,0.99,149,NaN,NaN,NaN,NaN,0
3,2020,120,0.93,0.89,0.93,1.0,1.0,1.0,1.0,32,1.00,0.95,0.90,1.00,70,0.56,0.71,1.00,0.56,18
4,2021,213,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,1.00,1.00,1.00,1.00,213,NaN,NaN,NaN,NaN,0
5,2022,62,1.00,1.00,1.00,1.0,1.0,1.0,1.0,62,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,29,0.83,0.45,0.91,NaN,NaN,NaN,NaN,0,0.83,0.91,1.00,0.83,29,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto WD2

In [4]:
# acc WD2 at1
WD2_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WD2_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WD2_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WD2_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,acc_remaining,f1_remaining,prec_remaining,rec_remaining,n_remaining,acc_wet_nature,f1_wet_nature,prec_wet_nature,rec_wet_nature,n_wet_nature
0,2017,372,0.92,0.92,0.92,NaN,NaN,NaN,NaN,0,1.00,0.92,0.85,1.00,170,0.85,0.92,1.00,0.85,202
1,2018,241,0.85,0.88,0.85,1.0,1.0,1.0,1.0,36,0.83,0.84,0.85,0.83,118,0.80,0.79,0.78,0.80,87
2,2019,247,1.00,1.00,1.00,1.0,1.0,1.0,1.0,41,1.00,1.00,1.00,1.00,206,NaN,NaN,NaN,NaN,0
3,2020,87,0.99,0.98,0.99,NaN,NaN,NaN,NaN,0,0.99,0.99,1.00,0.99,72,1.00,0.97,0.94,1.00,15
4,2021,202,0.98,0.49,0.99,NaN,NaN,NaN,NaN,0,0.98,0.99,1.00,0.98,202,NaN,NaN,NaN,NaN,0
5,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,36,1.00,1.00,1.00,1.0,1.0,1.0,1.0,36,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto WD3

In [5]:
# acc WD3 at1
WD3_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WD3_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WD3_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WD3_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,...,acc_semi-wet_nature,f1_semi-wet_nature,prec_semi-wet_nature,rec_semi-wet_nature,n_semi-wet_nature,acc_wet_nature,f1_wet_nature,prec_wet_nature,rec_wet_nature,n_wet_nature
0,2017,299,0.90,0.89,0.91,NaN,NaN,NaN,NaN,0,...,0.99,0.85,0.75,0.99,86,NaN,NaN,NaN,NaN,0
1,2018,212,0.96,0.71,0.97,0.76,0.86,1.0,0.76,33,...,0.98,0.99,1.00,0.98,45,NaN,NaN,NaN,NaN,0
2,2019,240,0.98,0.49,0.99,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,2020,313,0.65,0.50,0.59,NaN,NaN,NaN,NaN,0,...,0.24,0.32,0.51,0.24,101,0.24,0.38,1.0,0.24,42
4,2021,128,0.72,0.33,0.70,0.00,0.00,0.0,0.00,36,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
5,2022,36,1.00,1.00,1.00,1.00,1.00,1.0,1.00,36,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,79,0.75,0.45,0.85,0.90,0.95,1.0,0.90,10,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,31,1.00,1.00,1.00,1.00,1.00,1.0,1.00,31,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto WD4

In [6]:
# acc WD4 at1
WD4_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WD4_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WD4_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WD4_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,...,acc_semi-wet_nature,f1_semi-wet_nature,prec_semi-wet_nature,rec_semi-wet_nature,n_semi-wet_nature,acc_wet_nature,f1_wet_nature,prec_wet_nature,rec_wet_nature,n_wet_nature
0,2017,297,0.85,0.45,0.85,NaN,NaN,NaN,NaN,0,...,0.23,0.38,1.00,0.23,60,NaN,NaN,NaN,NaN,0
1,2018,299,0.85,0.60,0.83,0.95,0.67,0.51,0.95,22,...,0.67,0.80,0.98,0.67,64,0.00,0.0,0.0,0.00,21
2,2019,150,1.00,1.00,1.00,1.00,1.00,1.00,1.00,62,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,2020,239,0.71,0.59,0.66,NaN,NaN,NaN,NaN,0,...,0.33,0.45,0.73,0.33,83,0.33,0.5,1.0,0.33,21
4,2021,265,1.00,1.00,1.00,1.00,1.00,1.00,1.00,4,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
5,2022,36,1.00,1.00,1.00,1.00,1.00,1.00,1.00,36,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,34,0.97,0.66,0.98,1.00,1.00,1.00,1.00,10,...,0.96,0.98,1.00,0.96,24,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto WD5

In [7]:
# acc WD5 at1
WD5_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WD5_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WD5_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WD5_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,acc_remaining,f1_remaining,prec_remaining,rec_remaining,n_remaining,acc_semi-wet_nature,f1_semi-wet_nature,prec_semi-wet_nature,rec_semi-wet_nature,n_semi-wet_nature
0,2017,330,0.84,0.84,0.84,NaN,NaN,NaN,NaN,0,0.80,0.84,0.89,0.80,179,0.89,0.83,0.79,0.89,151
1,2018,236,0.94,0.94,0.95,0.91,0.95,1.0,0.91,23,1.00,0.90,0.82,1.00,59,0.93,0.96,1.00,0.93,154
2,2019,251,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,1.00,1.00,1.00,1.00,251,NaN,NaN,NaN,NaN,0
3,2020,41,0.27,0.18,0.17,0.00,0.00,0.0,0.00,28,NaN,NaN,NaN,NaN,0,0.85,0.54,0.39,0.85,13
4,2021,233,1.00,1.00,1.00,1.00,1.00,1.0,1.00,31,1.00,1.00,1.00,1.00,202,NaN,NaN,NaN,NaN,0
5,2022,27,0.30,0.15,0.46,0.30,0.46,1.0,0.30,27,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,108,0.96,0.66,0.98,1.00,1.00,1.0,1.00,36,0.94,0.97,1.00,0.94,72,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto WD6

In [8]:
# acc WD5 at1
WD6_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WD6_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WD6_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WD6_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,acc_remaining,f1_remaining,prec_remaining,rec_remaining,n_remaining,acc_semi-wet_nature,f1_semi-wet_nature,prec_semi-wet_nature,rec_semi-wet_nature,n_semi-wet_nature
0,2017,350,0.76,0.52,0.78,NaN,NaN,NaN,NaN,0,0.68,0.80,0.98,0.68,197,0.86,0.76,0.68,0.86,153
1,2018,274,0.88,0.91,0.88,0.97,0.99,1.0,0.97,36,0.99,0.87,0.78,0.99,107,0.77,0.86,0.98,0.77,131
2,2019,210,1.00,0.99,1.00,0.98,0.99,1.0,0.98,62,1.00,1.00,0.99,1.00,148,NaN,NaN,NaN,NaN,0
3,2020,134,0.63,0.40,0.56,0.18,0.30,1.0,0.18,28,1.00,0.81,0.68,1.00,78,0.07,0.09,0.13,0.07,28
4,2021,226,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,1.00,1.00,1.00,1.00,226,NaN,NaN,NaN,NaN,0
5,2022,16,0.25,0.20,0.40,0.25,0.40,1.0,0.25,16,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

## Carto s scores

### Carto S1

In [9]:
# acc s1 at1
s1_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="s1_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

s1_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\s1_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,...,acc_zure_vennen,f1_zure_vennen,prec_zure_vennen,rec_zure_vennen,n_zure_vennen,acc_zwakgebufferde_vennen,f1_zwakgebufferde_vennen,prec_zwakgebufferde_vennen,rec_zwakgebufferde_vennen,n_zwakgebufferde_vennen
0,2017,104,0.88,0.64,0.82,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
1,2018,249,0.67,0.38,0.64,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,40
2,2019,121,1.00,1.00,1.00,1.0,1.00,1.00,1.0,73,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,2020,222,0.93,0.51,0.93,1.0,0.99,0.98,1.0,42,...,0.43,0.6,1.0,0.43,21,0.0,0.0,0.0,0.0,3
4,2021,145,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
5,2022,30,1.00,1.00,1.00,1.0,1.00,1.00,1.0,30,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto S2

In [10]:
# acc s2 at1
s2_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="s2_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

s2_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\s2_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,...,acc_ven,f1_ven,prec_ven,rec_ven,n_ven,acc_vochtige_heiden,f1_vochtige_heiden,prec_vochtige_heiden,rec_vochtige_heiden,n_vochtige_heiden
0,2017,78,0.82,0.82,0.82,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,0.72,0.79,0.87,0.72,36
1,2018,268,0.79,0.67,0.77,1.0,0.83,0.71,1.0,48,...,0.13,0.23,1.0,0.13,23,0.81,0.77,0.73,0.81,73
2,2019,34,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,2020,170,0.92,0.55,0.93,1.0,1.00,1.00,1.0,36,...,0.14,0.25,1.0,0.14,7,NaN,NaN,NaN,NaN,0
4,2021,63,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
5,2022,16,0.75,0.43,0.86,NaN,NaN,NaN,NaN,0,...,0.75,0.86,1.0,0.75,16,NaN,NaN,NaN,NaN,0
6,2023,33,1.00,1.00,1.00,1.0,1.00,1.00,1.0,33,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,10,1.00,1.00,1.00,1.0,1.00,1.00,1.0,10,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto S3

In [11]:
# acc s3 at1
s3_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="s3_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

s3_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,...,acc_ven,f1_ven,prec_ven,rec_ven,n_ven,acc_vochtige_heiden,f1_vochtige_heiden,prec_vochtige_heiden,rec_vochtige_heiden,n_vochtige_heiden
0,2017,85,0.68,0.66,0.66,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,0.95,0.75,0.62,0.95,42
1,2018,226,0.66,0.36,0.65,NaN,NaN,NaN,NaN,0,...,0.00,0.00,0.0,0.00,21,1.00,0.77,0.63,1.00,94
2,2019,144,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,2020,62,0.89,0.65,0.91,1.0,1.0,1.0,1.0,36,...,0.56,0.72,1.0,0.56,16,NaN,NaN,NaN,NaN,0
4,2021,87,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
5,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,12,1.00,1.00,1.00,1.0,1.0,1.0,1.0,12,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,76,1.00,1.00,1.00,1.0,1.0,1.0,1.0,76,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

## Carto UC scores

### Carto UC1 at1 (2+1)

In [12]:
# acc UC1 at1
uc1_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="UC1_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

uc1_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\UC1_at1_gelderland_stacked_rstrs.tif
Warning: label mismatch between gdf and raster class map after cleaning.
  Present in gdf but not in raster CLASS-MAP: ['open water', 'remaining', 'wet nature']
  Present in raster CLASS-MAP but not in gdf: ['a', 'b', 'rest']
  This may reduce per-class scores (unmapped labels will never match).

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,acc_remaining,f1_remaining,prec_remaining,rec_remaining,n_remaining,acc_wet_nature,f1_wet_nature,prec_wet_nature,rec_wet_nature,n_wet_nature
0,2017,244,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,61,0.0,0.0,0.0,0.0,183
1,2018,337,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,229,0.0,0.0,0.0,0.0,108
2,2019,185,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36,0.0,0.0,0.0,0.0,149,NaN,NaN,NaN,NaN,0
3,2020,120,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32,0.0,0.0,0.0,0.0,70,0.0,0.0,0.0,0.0,18
4,2021,213,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,213,NaN,NaN,NaN,NaN,0
5,2022,62,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,29,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,29,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto UC3 (3+1)

In [13]:
# acc UC3 at1
uc3_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="UC3_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

uc3_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\UC3_at1_gelderland_stacked_rstrs.tif
Warning: label mismatch between gdf and raster class map after cleaning.
  Present in gdf but not in raster CLASS-MAP: ['open water', 'remaining', 'semi-wet nature', 'wet nature']
  Present in raster CLASS-MAP but not in gdf: ['a', 'b', 'c', 'rest']
  This may reduce per-class scores (unmapped labels will never match).

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,...,acc_semi-wet_nature,f1_semi-wet_nature,prec_semi-wet_nature,rec_semi-wet_nature,n_semi-wet_nature,acc_wet_nature,f1_wet_nature,prec_wet_nature,rec_wet_nature,n_wet_nature
0,2017,299,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,...,0.0,0.0,0.0,0.0,86,NaN,NaN,NaN,NaN,0
1,2018,212,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33,...,0.0,0.0,0.0,0.0,45,NaN,NaN,NaN,NaN,0
2,2019,240,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,2020,313,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,...,0.0,0.0,0.0,0.0,101,0.0,0.0,0.0,0.0,42
4,2021,128,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
5,2022,36,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto UC5 (2+1)

In [14]:
# acc UC5 at1
uc5_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="UC5_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

uc5_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\UC5_at1_gelderland_stacked_rstrs.tif
Warning: label mismatch between gdf and raster class map after cleaning.
  Present in gdf but not in raster CLASS-MAP: ['open water', 'remaining', 'semi-wet nature']
  Present in raster CLASS-MAP but not in gdf: ['a', 'b', 'c', 'd', 'rest']
  This may reduce per-class scores (unmapped labels will never match).

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,acc_remaining,f1_remaining,prec_remaining,rec_remaining,n_remaining,acc_semi-wet_nature,f1_semi-wet_nature,prec_semi-wet_nature,rec_semi-wet_nature,n_semi-wet_nature
0,2017,330,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,179,0.0,0.0,0.0,0.0,151
1,2018,236,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23,0.0,0.0,0.0,0.0,59,0.0,0.0,0.0,0.0,154
2,2019,251,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,251,NaN,NaN,NaN,NaN,0
3,2020,41,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,13
4,2021,233,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31,0.0,0.0,0.0,0.0,202,NaN,NaN,NaN,NaN,0
5,2022,27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,108,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36,0.0,0.0,0.0,0.0,72,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

## Carto WDNF

### Carto WDNF1

In [15]:
# result_stats WDNF1 at1
WDNF1_at1__result_stats_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WDNF1_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WDNF1_at1__result_stats_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WDNF1_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,acc_remaining,f1_remaining,prec_remaining,rec_remaining,n_remaining,acc_wet_nature,f1_wet_nature,prec_wet_nature,rec_wet_nature,n_wet_nature
0,2017,135,0.92,0.90,0.92,NaN,NaN,NaN,NaN,0,0.93,0.94,0.96,0.93,97,0.89,0.86,0.83,0.89,38
1,2018,290,0.84,0.73,0.87,1.00,0.42,0.26,1.00,10,1.00,0.89,0.80,1.00,66,0.79,0.88,1.00,0.79,214
2,2019,276,1.00,0.99,1.00,0.98,0.99,1.00,0.98,58,1.00,1.00,1.00,1.00,218,NaN,NaN,NaN,NaN,0
3,2020,219,0.96,0.95,0.96,1.00,1.00,1.00,1.00,4,0.95,0.97,1.00,0.95,181,1.00,0.88,0.79,1.00,34
4,2021,89,0.98,0.49,0.99,NaN,NaN,NaN,NaN,0,0.98,0.99,1.00,0.98,89,NaN,NaN,NaN,NaN,0
5,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,169,0.97,0.66,0.98,1.00,1.00,1.00,1.00,36,0.96,0.98,1.00,0.96,133,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto WDNF2

In [16]:
# acc WD2 at1
WDNF2_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WDNF2_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WDNF2_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WDNF2_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,acc_remaining,f1_remaining,prec_remaining,rec_remaining,n_remaining,acc_wet_nature,f1_wet_nature,prec_wet_nature,rec_wet_nature,n_wet_nature
0,2017,318,0.84,0.68,0.82,NaN,NaN,NaN,NaN,0,0.96,0.91,0.86,0.96,255,0.35,0.46,0.69,0.35,63
1,2018,305,0.69,0.64,0.69,1.00,0.53,0.36,1.00,10,1.00,0.74,0.59,1.00,110,0.49,0.66,1.00,0.49,185
2,2019,128,0.99,0.99,0.99,0.98,0.99,1.00,0.98,58,1.00,0.99,0.99,1.00,70,NaN,NaN,NaN,NaN,0
3,2020,210,0.91,0.86,0.90,1.00,1.00,1.00,1.00,4,1.00,0.95,0.91,1.00,173,0.45,0.62,1.00,0.45,33
4,2021,174,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,1.00,1.00,1.00,1.00,174,NaN,NaN,NaN,NaN,0
5,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,36,1.00,1.00,1.00,1.00,1.00,1.00,1.00,36,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto WDNF3

In [17]:
# acc WD3 at1
WDNF3_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WDNF3_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WDNF3_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WDNF3_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,...,acc_semi-wet_nature,f1_semi-wet_nature,prec_semi-wet_nature,rec_semi-wet_nature,n_semi-wet_nature,acc_wet_nature,f1_wet_nature,prec_wet_nature,rec_wet_nature,n_wet_nature
0,2017,134,0.99,0.98,0.99,NaN,NaN,NaN,NaN,0,...,0.99,1.0,1.00,0.99,120,NaN,NaN,NaN,NaN,0
1,2018,353,0.70,0.50,0.66,1.0,0.53,0.36,1.0,10,...,0.48,0.6,0.81,0.48,135,0.03,0.05,0.33,0.03,36
2,2019,226,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,2020,193,0.79,0.22,0.88,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,0.00,0.00,0.00,0.00,4
4,2021,248,1.00,1.00,1.00,1.0,1.00,1.00,1.0,12,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
5,2022,36,1.00,1.00,1.00,1.0,1.00,1.00,1.0,36,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,121,0.82,0.62,0.90,1.0,1.00,1.00,1.0,36,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,30,1.00,1.00,1.00,1.0,1.00,1.00,1.0,30,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto WDNF4

In [18]:
# acc WDNF4 at1
WDNF4_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WDNF4_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WDNF4_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WDNF4_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,...,acc_semi-wet_nature,f1_semi-wet_nature,prec_semi-wet_nature,rec_semi-wet_nature,n_semi-wet_nature,acc_wet_nature,f1_wet_nature,prec_wet_nature,rec_wet_nature,n_wet_nature
0,2017,171,0.93,0.92,0.93,NaN,NaN,NaN,NaN,0,...,0.91,0.95,0.98,0.91,116,NaN,NaN,NaN,NaN,0
1,2018,393,0.83,0.57,0.81,0.76,0.65,0.57,0.76,33,...,0.55,0.71,1.00,0.55,83,0.00,0.0,0.0,0.00,21
2,2019,408,1.00,1.00,1.00,1.00,1.00,1.00,1.00,36,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,2020,263,0.89,0.75,0.88,0.99,0.99,1.00,0.99,72,...,0.61,0.67,0.73,0.61,31,0.25,0.4,1.0,0.25,20
4,2021,108,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
5,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,4,1.00,1.00,1.00,1.00,1.00,1.00,1.00,4,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto WDNF5

In [19]:
# acc WDNF5 at1
WDNF5_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WDNF5_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WDNF5_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WDNF5_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,acc_remaining,f1_remaining,prec_remaining,rec_remaining,n_remaining,acc_semi-wet_nature,f1_semi-wet_nature,prec_semi-wet_nature,rec_semi-wet_nature,n_semi-wet_nature
0,2017,247,0.67,0.67,0.66,NaN,NaN,NaN,NaN,0,0.96,0.69,0.54,0.96,96,0.49,0.65,0.95,0.49,151
1,2018,308,0.84,0.85,0.85,0.9,0.95,1.0,0.9,59,0.77,0.86,0.98,0.77,183,1.00,0.74,0.59,1.00,66
2,2019,116,0.99,0.66,1.00,1.0,1.00,1.0,1.0,36,0.99,0.99,1.00,0.99,80,NaN,NaN,NaN,NaN,0
3,2020,157,0.66,0.27,0.74,0.0,0.00,0.0,0.0,14,0.73,0.81,0.92,0.73,143,NaN,NaN,NaN,NaN,0
4,2021,209,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,1.00,1.00,1.00,1.00,209,NaN,NaN,NaN,NaN,0
5,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,42,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,1.00,1.00,1.00,1.00,42,NaN,NaN,NaN,NaN,0
7,2024,36,1.00,1.00,1.00,1.0,1.00,1.0,1.0,36,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

### Carto WDNF6

In [20]:
# acc WDNF5 at1
WDNF6_at1__acc_df = building_carto_clas_acc_dfs(
    carto_output_processing__dir=carto_output_main__dir,
    carto_validation_data__dir=validation_cart__RD__gpkgs_dir,
    carto_validation_label_col="type",
    carto_validation_year_col="years",
    run_id="WDNF6_plusOW_p80_tmp2_cart_at1__gelderland__RD",
)

WDNF6_at1__acc_df

in Carto-files the following years were found and used: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Warning: output exists and overwrite=False; skipping: D:\Thesis\10.Thesis_Data\04_carto_output\02_stacked_rstrs\WDNF6_at1_gelderland_stacked_rstrs.tif

,clas_year,n,acc,macro_f1,weighted_f1,acc_open_water,f1_open_water,prec_open_water,rec_open_water,n_open_water,acc_remaining,f1_remaining,prec_remaining,rec_remaining,n_remaining,acc_semi-wet_nature,f1_semi-wet_nature,prec_semi-wet_nature,rec_semi-wet_nature,n_semi-wet_nature
0,2017,288,0.73,0.67,0.69,NaN,NaN,NaN,NaN,0,1.00,0.81,0.68,1.00,165,0.37,0.54,1.00,0.37,123
1,2018,216,0.80,0.83,0.80,0.92,0.96,1.0,0.92,38,0.67,0.75,0.85,0.67,93,0.88,0.78,0.69,0.88,85
2,2019,213,1.00,1.00,1.00,NaN,NaN,NaN,NaN,0,1.00,1.00,1.00,1.00,213,NaN,NaN,NaN,NaN,0
3,2020,135,0.92,0.49,0.93,0.31,0.48,1.0,0.31,16,1.00,0.99,0.98,1.00,119,NaN,NaN,NaN,NaN,0
4,2021,220,1.00,1.00,1.00,1.00,1.00,1.0,1.00,46,1.00,1.00,1.00,1.00,174,NaN,NaN,NaN,NaN,0
5,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
6,2023,36,1.00,1.00,1.00,1.00,1.00,1.0,1.00,36,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
7,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
8,2025,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

End of the Notebook